use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::sync::atomic::{AtomicU64, Ordering};

static NEXT_TEMP: AtomicU64 = AtomicU64::new(0);

struct TestDir(PathBuf);

impl TestDir {
    fn new() -> Self {
        let unique = NEXT_TEMP.fetch_add(1, Ordering::Relaxed);
        let path =
            std::env::temp_dir().join(format!("ruac-annotations-{}-{unique}", std::process::id()));
        fs::create_dir_all(&path).unwrap();
        Self(path)
    }
}

impl Drop for TestDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn source() -> &'static str {
    r#"
#[targets(function)]
#[retention(runtime)]
pub annotation Route(method: String, path: String);

#[Route(path = "/users", method = "GET")]
pub fn users() -> String {
    "users"
}

let routes = Annotations::find("Route");
print("routes={}", routes.len());
"#
}

#[test]
fn runtime_annotations_are_in_artifact_and_bundle_registry() {
    let project = TestDir::new();
    let input = project.0.join("main.rua");
    fs::write(&input, source()).unwrap();

    let artifact = ruac::compile_path_artifact(&input).unwrap();
    assert_eq!(artifact.annotations.definitions().len(), 1);
    assert_eq!(artifact.annotations.instances().len(), 1);
    assert!(
        artifact
            .source
            .contains("package.loaded[\"rua_annotations\"]")
    );
    assert!(artifact.source.contains("annotation = \"Route\""));
    let registration = artifact.source.find("set_entries").unwrap();
    let query = artifact.source.find("local routes").unwrap();
    assert!(
        registration < query,
        "metadata must exist before chunk initializers"
    );
}

#[test]
fn modules_emit_one_aggregated_runtime_annotation_file() {
    let project = TestDir::new();
    let input = project.0.join("main.rua");
    fs::write(&input, source()).unwrap();

    let artifact = ruac::compile_path_modules_artifact(&input).unwrap();
    let paths = artifact
        .modules
        .iter()
        .map(|module| module.output_path.as_str())
        .collect::<Vec<_>>();
    assert_eq!(paths, ["main.lua", "rua_annotations.lua"]);
    let registry = artifact
        .modules
        .iter()
        .find(|module| module.output_path == "rua_annotations.lua")
        .unwrap();
    assert!(registry.source.contains("require(\"rua_std\").annotations"));
    assert!(registry.source.contains("M.set_entries(entries)"));
    assert!(!registry.source.contains("require(\"main\")"));
}

#[test]
fn aggregated_runtime_annotations_include_targets_from_multiple_modules() {
    let project = TestDir::new();
    let input = project.0.join("main.rua");
    fs::write(
        &input,
        r#"
use metadata::Route;

#[Route(name = "root")]
pub fn root_handler() -> String { "root" }

print("{}", handlers::child_handler());
"#,
    )
    .unwrap();
    fs::write(
        project.0.join("metadata.rua"),
        r#"
#[targets(function)]
#[retention(runtime)]
pub annotation Route(name: String);
"#,
    )
    .unwrap();
    fs::write(
        project.0.join("handlers.rua"),
        r#"
use metadata::Route;

#[Route(name = "child")]
pub fn child_handler() -> String { "child" }
"#,
    )
    .unwrap();

    let artifact = ruac::compile_path_modules_artifact(&input).unwrap();
    let metadata = artifact
        .modules
        .iter()
        .filter(|module| module.output_path == "rua_annotations.lua")
        .collect::<Vec<_>>();
    assert_eq!(metadata.len(), 1);
    assert!(
        artifact
            .modules
            .iter()
            .all(|module| !module.output_path.ends_with(".meta.lua"))
    );
    let source = &metadata[0].source;
    assert_eq!(
        source.matches("annotation = \"metadata::Route\"").count(),
        2
    );
    assert!(source.contains("module = \"main\""), "{source}");
    assert!(source.contains("module = \"handlers\""), "{source}");
}

#[test]
fn modules_build_removes_only_stale_generated_annotation_files() {
    let project = TestDir::new();
    let input = project.0.join("main.rua");
    let output = project.0.join("dist");
    let legacy = output.join("nested/handler.meta.lua");
    let user_file = output.join("keep.meta.lua");
    fs::write(&input, source()).unwrap();
    fs::create_dir_all(legacy.parent().unwrap()).unwrap();
    fs::write(
        &legacy,
        "-- Generated by ruac. Runtime annotation metadata ABI 1.\nreturn {}\n",
    )
    .unwrap();
    fs::write(&user_file, "return { user_owned = true }\n").unwrap();

    let build = Command::new(env!("CARGO_BIN_EXE_ruac"))
        .args([
            "build",
            "main.rua",
            "--emit",
            "modules",
            "--out-dir",
            "dist",
        ])
        .current_dir(&project.0)
        .output()
        .unwrap();
    assert!(
        build.status.success(),
        "{}",
        String::from_utf8_lossy(&build.stderr)
    );
    assert!(!legacy.exists());
    assert!(user_file.exists());
    assert!(output.join("rua_annotations.lua").is_file());

    fs::write(&input, "pub fn users() -> String { \"users\" }\n").unwrap();
    let rebuild = Command::new(env!("CARGO_BIN_EXE_ruac"))
        .args([
            "build",
            "main.rua",
            "--emit",
            "modules",
            "--out-dir",
            "dist",
        ])
        .current_dir(&project.0)
        .output()
        .unwrap();
    assert!(
        rebuild.status.success(),
        "{}",
        String::from_utf8_lossy(&rebuild.stderr)
    );
    assert!(!output.join("rua_annotations.lua").exists());
    assert!(user_file.exists());
}

#[test]
fn qualified_runtime_annotation_key_matches_metadata_and_query_api() {
    let project = TestDir::new();
    let input = project.0.join("main.rua");
    fs::write(
        &input,
        r#"
use metadata::Trace;

#[Trace(name = "entry")]
pub fn entry() {}

let traces = Annotations::find("metadata::Trace");
print("traces={}", traces.len());
"#,
    )
    .unwrap();
    fs::write(
        project.0.join("metadata.rua"),
        r#"
#[targets(function)]
#[retention(runtime)]
pub annotation Trace(name: String);
"#,
    )
    .unwrap();

    let artifact = ruac::compile_path_artifact(&input).unwrap();
    assert!(artifact.source.contains("annotation = \"metadata::Trace\""));
    let metadata = ruac::compile_path_metadata(&input, None).unwrap();
    assert!(metadata.contains("annotation = \"metadata::Trace\""));

    let modules = ruac::compile_path_modules_artifact(&input).unwrap();
    let registry = modules
        .modules
        .iter()
        .find(|module| module.output_path == "rua_annotations.lua")
        .unwrap();
    assert!(registry.source.contains("annotation = \"metadata::Trace\""));
}

#[test]
fn no_runtime_annotation_adds_no_registry_file() {
    let project = TestDir::new();
    let input = project.0.join("main.rua");
    fs::write(&input, "pub fn users() -> String { \"users\" }\n").unwrap();

    let artifact = ruac::compile_path_modules_artifact(&input).unwrap();
    assert_eq!(
        artifact
            .modules
            .iter()
            .map(|module| module.output_path.as_str())
            .collect::<Vec<_>>(),
        ["main.lua"]
    );
}

#[test]
fn private_runtime_target_is_rejected() {
    let project = TestDir::new();
    let input = project.0.join("main.rua");
    fs::write(
        &input,
        r#"
        #[targets(function)]
        #[retention(runtime)]
        annotation Route();
        #[Route]
        fn private_handler() {}
        "#,
    )
    .unwrap();
    let error = ruac::compile_path(&input).unwrap_err();
    assert!(error.contains("requires a public target"));
}

#[test]
fn metadata_command_exports_filtered_resolved_toml() {
    let project = TestDir::new();
    let input = project.0.join("main.rua");
    fs::write(&input, source()).unwrap();

    let metadata = ruac::compile_path_metadata(&input, Some("Route")).unwrap();
    assert!(metadata.contains("version = 1"));
    assert!(metadata.contains("name = \"Route\""));
    assert!(metadata.contains("annotation = \"Route\""));
    assert!(metadata.contains("target = \"users\""));
    assert!(metadata.contains("method = \"GET\""));

    let output = Command::new(env!("CARGO_BIN_EXE_ruac"))
        .args([
            "metadata",
            "main.rua",
            "--annotation",
            "Route",
            "--format",
            "toml",
        ])
        .current_dir(&project.0)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(String::from_utf8(output.stdout).unwrap(), metadata);
}
