//! Lua 5.5 source backend.
//!
//! Expression-to-statement lowering uses a "destination" model (docs §4.1):
//! every expression is generated *to* a `Dest` (discard / assign / return).
//! Control-flow expressions push the same `Dest` into their branches; only
//! value-producing control-flow in operand position hoists a temporary.
//!
//! Data mapping (docs §4.2 / §4.3):
//!   struct        -> table + metatable (methods in `__index`)
//!   enum variant  -> { tag = "Name", ... } + metatable
//!   Option        -> pure nil: Some(v) => v, None => nil
//!   Result        -> Ok(v) => { ok = v }, Err(e) => { err = e }

use crate::ast::*;
use crate::typeck::TypeInfo;
use std::collections::{HashMap, HashSet};

#[derive(Clone)]
enum Dest {
    Discard,
    Var(String),
    Return,
}

#[derive(Clone, Copy)]
enum VarShape {
    Unit,
    Tuple,
    Struct,
}

/// Type/variant information gathered before codegen so paths like
/// `Shape::Circle` and bare variants can be resolved without a type checker.
struct Ctx {
    structs: HashSet<String>,
    /// enum name -> (variant name -> shape)
    enums: HashMap<String, HashMap<String, VarShape>>,
    /// variant name -> enum name (only for variants with a unique name)
    variant_enum: HashMap<String, String>,
}

impl Ctx {
    fn collect(prog: &Program) -> Ctx {
        let mut structs = HashSet::new();
        let mut enums: HashMap<String, HashMap<String, VarShape>> = HashMap::new();
        let mut variant_enum: HashMap<String, String> = HashMap::new();
        let mut ambiguous: HashSet<String> = HashSet::new();

        // Types are keyed by simple name (root + all modules); cross-module
        // references resolve via qualified `::` paths at the emit sites.
        Self::collect_items(
            &prog.items,
            &mut structs,
            &mut enums,
            &mut variant_enum,
            &mut ambiguous,
        );
        for a in ambiguous {
            variant_enum.remove(&a);
        }
        Ctx {
            structs,
            enums,
            variant_enum,
        }
    }

    fn collect_items(
        items: &[Item],
        structs: &mut HashSet<String>,
        enums: &mut HashMap<String, HashMap<String, VarShape>>,
        variant_enum: &mut HashMap<String, String>,
        ambiguous: &mut HashSet<String>,
    ) {
        for item in items {
            match item {
                Item::Struct(s) => {
                    structs.insert(s.name.clone());
                }
                Item::Enum(e) => {
                    let mut vs = HashMap::new();
                    for v in &e.variants {
                        let shape = match &v.kind {
                            VariantKind::Unit => VarShape::Unit,
                            VariantKind::Tuple(_) => VarShape::Tuple,
                            VariantKind::Struct(_) => VarShape::Struct,
                        };
                        vs.insert(v.name.clone(), shape);
                        if variant_enum.contains_key(&v.name) {
                            ambiguous.insert(v.name.clone());
                        } else {
                            variant_enum.insert(v.name.clone(), e.name.clone());
                        }
                    }
                    enums.insert(e.name.clone(), vs);
                }
                Item::Mod(m) => {
                    Self::collect_items(&m.items, structs, enums, variant_enum, ambiguous);
                }
                _ => {}
            }
        }
    }

    /// Resolve a path to a user enum variant (not Option/Result built-ins).
    fn resolve_variant(&self, segs: &[String]) -> Option<(String, String, VarShape)> {
        if segs.len() >= 2 {
            let en = &segs[segs.len() - 2];
            let var = &segs[segs.len() - 1];
            let shape = self.enums.get(en)?.get(var)?;
            Some((en.clone(), var.clone(), shape.clone()))
        } else if segs.len() == 1 {
            let var = &segs[0];
            let en = self.variant_enum.get(var)?;
            let shape = self.enums.get(en)?.get(var)?;
            Some((en.clone(), var.clone(), shape.clone()))
        } else {
            None
        }
    }
}

pub fn generate(prog: &Program, info: &TypeInfo) -> String {
    let mut cg = Codegen {
        out: String::new(),
        indent: 0,
        tmp: 0,
        ctx: Ctx::collect(prog),
        uses_rt: false,
        info,
    };
    cg.gen_program(prog);

    let mut result = String::from("-- Generated by ruac (Rua -> Lua 5.5). Do not edit by hand.\n");
    if cg.uses_rt {
        result.push_str("local rt = require(\"rua_rt\")\n");
    }
    result.push_str(&cg.out);
    result
}

struct Codegen<'a> {
    out: String,
    indent: usize,
    tmp: usize,
    ctx: Ctx,
    /// Set when any generated code references the `rua_rt` runtime shim.
    uses_rt: bool,
    info: &'a TypeInfo,
}

impl Codegen<'_> {
    fn line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) {
        self.out.push('\n');
    }

    fn fresh_tmp(&mut self) -> String {
        self.tmp += 1;
        format!("__t{}", self.tmp)
    }

    // --- program ----------------------------------------------------------

    fn gen_program(&mut self, prog: &Program) {
        let struct_names: Vec<&str> = prog
            .items
            .iter()
            .filter_map(|i| match i {
                Item::Struct(s) => Some(s.name.as_str()),
                _ => None,
            })
            .collect();
        let enum_names: Vec<&str> = prog
            .items
            .iter()
            .filter_map(|i| match i {
                Item::Enum(e) => Some(e.name.as_str()),
                _ => None,
            })
            .collect();
        let fn_names: Vec<&str> = prog
            .items
            .iter()
            .filter_map(|i| match i {
                Item::Fn(f) => Some(f.name.as_str()),
                _ => None,
            })
            .collect();
        // Declaration-only (`.ruai`) modules emit nothing and are not locals:
        // references to them resolve to host-provided globals (e.g. `moon`).
        let mod_names: Vec<&str> = prog
            .items
            .iter()
            .filter_map(|i| match i {
                Item::Mod(m) if !m.is_decl => Some(m.name.as_str()),
                _ => None,
            })
            .collect();
        // `use` imports are desugared away before codegen (paths are already
        // fully qualified), so no runtime alias locals are needed.
        let mut all: Vec<&str> = Vec::new();
        all.extend(&struct_names);
        all.extend(&enum_names);
        all.extend(&fn_names);
        all.extend(&mod_names);
        if !all.is_empty() {
            self.line(&format!("local {}", all.join(", ")));
        }

        // Class tables (with `__index`) for structs and enums so their values
        // can carry methods.
        for name in struct_names.iter().chain(enum_names.iter()) {
            self.line(&format!("{name} = {{}}"));
            self.line(&format!("{name}.__index = {name}"));
        }

        // Trait table across all scopes (root + modules), keyed by simple name,
        // for resolving inherited default methods in `impl Trait for Type`.
        let mut traits: HashMap<&str, &TraitDecl> = HashMap::new();
        collect_traits(&prog.items, &mut traits);

        for item in &prog.items {
            if let Item::Fn(f) = item {
                self.gen_free_fn(f);
            }
        }
        for item in &prog.items {
            if let Item::Mod(m) = item {
                if !m.is_decl {
                    self.gen_mod(m, &traits);
                }
            }
        }
        self.gen_impls(&prog.items, &traits);

        if prog
            .items
            .iter()
            .any(|i| matches!(i, Item::Fn(f) if f.name == "main" && f.params.is_empty()))
        {
            self.blank();
            self.line("main()");
        }
    }

    /// Emit an inline module as a Lua table populated inside a `do` block, so
    /// sibling items see each other as block locals while cross-module access
    /// goes through the table (`mod::item` -> `mod.item`). Supports `fn`,
    /// `struct`/`enum`/`impl`/`trait`, and nested `mod` (co-located impls).
    fn gen_mod(&mut self, m: &ModDecl, traits: &HashMap<&str, &TraitDecl>) {
        self.blank();
        self.line(&format!("{} = {{}}", m.name));
        self.line("do");
        self.indent += 1;

        // All named items become block locals (types, fns, nested mods) so the
        // module body can refer to them without qualification.
        let locals: Vec<&str> = m
            .items
            .iter()
            .filter_map(|i| match i {
                Item::Fn(f) => Some(f.name.as_str()),
                Item::Struct(s) => Some(s.name.as_str()),
                Item::Enum(e) => Some(e.name.as_str()),
                Item::Mod(md) if !md.is_decl => Some(md.name.as_str()),
                _ => None,
            })
            .collect();
        if !locals.is_empty() {
            self.line(&format!("local {}", locals.join(", ")));
        }

        // Class tables for module-local structs/enums.
        for item in &m.items {
            match item {
                Item::Struct(s) => {
                    self.line(&format!("{0} = {{}}; {0}.__index = {0}", s.name));
                }
                Item::Enum(e) => {
                    self.line(&format!("{0} = {{}}; {0}.__index = {0}", e.name));
                }
                _ => {}
            }
        }

        for item in &m.items {
            match item {
                Item::Fn(f) => self.gen_free_fn(f),
                Item::Mod(md) if !md.is_decl => self.gen_mod(md, traits),
                _ => {}
            }
        }
        self.gen_impls(&m.items, traits);

        // Publish members onto the module table.
        for item in &m.items {
            let name = match item {
                Item::Fn(f) => Some(f.name.as_str()),
                Item::Struct(s) => Some(s.name.as_str()),
                Item::Enum(e) => Some(e.name.as_str()),
                Item::Mod(md) if !md.is_decl => Some(md.name.as_str()),
                _ => None,
            };
            if let Some(n) = name {
                self.line(&format!("{}.{} = {}", m.name, n, n));
            }
        }

        self.indent -= 1;
        self.line("end");
    }

    /// Emit all `impl` blocks in `items` (methods, operator aliases, inherited
    /// trait defaults). The type's class table is a same-scope local, so
    /// `function Type.method(...)` binds correctly at root or inside a module.
    fn gen_impls(&mut self, items: &[Item], traits: &HashMap<&str, &TraitDecl>) {
        for item in items {
            if let Item::Impl(im) = item {
                let mut overridden: HashSet<&str> = HashSet::new();
                for m in &im.methods {
                    overridden.insert(m.name.as_str());
                    self.gen_method(&im.type_name, m);
                    if let Some(tr) = &im.trait_name {
                        if let Some(meta) = op_alias(tr, &m.name) {
                            self.line(&format!("{0}.{1} = {0}.{2}", im.type_name, meta, m.name));
                        }
                    }
                }
                if let Some(tr) = &im.trait_name {
                    if let Some(td) = traits.get(tr.as_str()) {
                        for tm in &td.methods {
                            if tm.default.is_some() && !overridden.contains(tm.name.as_str()) {
                                self.gen_trait_default(&im.type_name, tm);
                                if let Some(meta) = op_alias(tr, &tm.name) {
                                    self.line(&format!(
                                        "{0}.{1} = {0}.{2}",
                                        im.type_name, meta, tm.name
                                    ));
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    fn gen_free_fn(&mut self, f: &FnDecl) {
        self.blank();
        let params: Vec<&str> = f.params.iter().map(|p| p.name.as_str()).collect();
        self.line(&format!("function {}({})", f.name, params.join(", ")));
        self.indent += 1;
        self.gen_block_to(&f.body, &Dest::Return);
        self.indent -= 1;
        self.line("end");
    }

    fn gen_method(&mut self, type_name: &str, m: &FnDecl) {
        self.blank();
        let params: Vec<&str> = m.params.iter().map(|p| p.name.as_str()).collect();
        // `:` gives an implicit `self`; `.` for associated functions.
        let sep = if m.has_self { ":" } else { "." };
        self.line(&format!(
            "function {}{}{}({})",
            type_name,
            sep,
            m.name,
            params.join(", ")
        ));
        self.indent += 1;
        self.gen_block_to(&m.body, &Dest::Return);
        self.indent -= 1;
        self.line("end");
    }

    fn gen_trait_default(&mut self, type_name: &str, tm: &TraitMethod) {
        self.blank();
        let params: Vec<&str> = tm.params.iter().map(|p| p.name.as_str()).collect();
        let sep = if tm.has_self { ":" } else { "." };
        self.line(&format!(
            "function {}{}{}({})",
            type_name,
            sep,
            tm.name,
            params.join(", ")
        ));
        self.indent += 1;
        // `default` is guaranteed Some by the caller.
        if let Some(body) = &tm.default {
            self.gen_block_to(body, &Dest::Return);
        }
        self.indent -= 1;
        self.line("end");
    }

    // --- statements --------------------------------------------------------

    fn gen_stmt(&mut self, s: &Stmt) {
        match s {
            Stmt::Let { name, init, .. } => {
                if needs_hoist(init) {
                    self.line(&format!("local {}", name));
                    self.gen_expr_to(init, &Dest::Var(name.clone()));
                } else {
                    let v = self.gen_inline(init);
                    self.line(&format!("local {} = {}", name, v));
                }
            }
            Stmt::Expr(e) => self.gen_expr_to(e, &Dest::Discard),
            Stmt::Return(opt) => {
                self.line("do");
                self.indent += 1;
                match opt {
                    Some(e) => self.gen_expr_to(e, &Dest::Return),
                    None => self.line("return"),
                }
                self.indent -= 1;
                self.line("end");
            }
            Stmt::While { cond, body } => {
                let c = self.gen_inline(cond);
                self.line(&format!("while {} do", c));
                self.indent += 1;
                self.gen_block_to(body, &Dest::Discard);
                self.line("::continue::");
                self.indent -= 1;
                self.line("end");
            }
            Stmt::Loop { body } => {
                self.line("while true do");
                self.indent += 1;
                self.gen_block_to(body, &Dest::Discard);
                self.line("::continue::");
                self.indent -= 1;
                self.line("end");
            }
            Stmt::For { var, iter, body, .. } => self.gen_for(var, iter, body),
            Stmt::WhileLet { pat, expr, body } => {
                self.line("while true do");
                self.indent += 1;
                let m = self.fresh_tmp();
                let s = self.gen_inline(expr);
                self.line(&format!("local {} = {}", m, s));
                let mut tests = Vec::new();
                let mut binds = Vec::new();
                self.pat_test(pat, &m, &mut tests, &mut binds);
                let cond = if tests.is_empty() {
                    "true".to_string()
                } else {
                    tests.join(" and ")
                };
                self.line(&format!("if {} then", cond));
                self.indent += 1;
                for (name, subj) in &binds {
                    self.line(&format!("local {} = {}", name, subj));
                }
                self.gen_block_to(body, &Dest::Discard);
                self.indent -= 1;
                self.line("else");
                self.indent += 1;
                self.line("break");
                self.indent -= 1;
                self.line("end");
                self.line("::continue::");
                self.indent -= 1;
                self.line("end");
            }
            Stmt::Break => self.line("break"),
            Stmt::Continue => self.line("goto continue"),
        }
    }

    fn gen_for(&mut self, var: &str, iter: &Expr, body: &Block) {
        if let ExprKind::Range {
            start,
            end,
            inclusive,
        } = &iter.kind
        {
            let s = self.gen_inline(start);
            let e = self.gen_inline(end);
            let stop = if *inclusive {
                e
            } else {
                format!("({}) - 1", e)
            };
            self.line(&format!("for {} = {}, {} do", var, s, stop));
            self.indent += 1;
            self.gen_block_to(body, &Dest::Discard);
            self.line("::continue::");
            self.indent -= 1;
            self.line("end");
        } else {
            // General iterable: a Vec `{ [0..n-1], n = len }`.
            let it = self.gen_inline(iter);
            let holder = self.fresh_tmp();
            self.line(&format!("local {} = {}", holder, it));
            let idx = self.fresh_tmp();
            self.line(&format!("for {} = 0, {}.n - 1 do", idx, holder));
            self.indent += 1;
            self.line(&format!("local {} = {}[{}]", var, holder, idx));
            self.gen_block_to(body, &Dest::Discard);
            self.line("::continue::");
            self.indent -= 1;
            self.line("end");
        }
    }

    // --- expression to destination ----------------------------------------

    fn gen_block_to(&mut self, block: &Block, dest: &Dest) {
        for s in &block.stmts {
            self.gen_stmt(s);
        }
        match &block.tail {
            Some(e) => self.gen_expr_to(e, dest),
            None => {
                if let Dest::Var(d) = dest {
                    self.line(&format!("{} = nil", d));
                }
            }
        }
    }

    fn gen_expr_to(&mut self, e: &Expr, dest: &Dest) {
        match &e.kind {
            ExprKind::If {
                cond,
                then_block,
                else_block,
            } => {
                let c = self.gen_inline(cond);
                self.line(&format!("if {} then", c));
                self.indent += 1;
                self.gen_block_to(then_block, dest);
                self.indent -= 1;
                match else_block.as_deref() {
                    Some(ElseBranch::Block(b)) => {
                        self.line("else");
                        self.indent += 1;
                        self.gen_block_to(b, dest);
                        self.indent -= 1;
                    }
                    Some(ElseBranch::If(inner)) => {
                        self.line("else");
                        self.indent += 1;
                        self.gen_expr_to(inner, dest);
                        self.indent -= 1;
                    }
                    None => {
                        if let Dest::Var(d) = dest {
                            self.line("else");
                            self.indent += 1;
                            self.line(&format!("{} = nil", d));
                            self.indent -= 1;
                        }
                    }
                }
                self.line("end");
            }
            ExprKind::IfLet {
                pat,
                expr,
                then_block,
                else_block,
            } => {
                let m = self.fresh_tmp();
                let s = self.gen_inline(expr);
                self.line(&format!("local {} = {}", m, s));
                let mut tests = Vec::new();
                let mut binds = Vec::new();
                self.pat_test(pat, &m, &mut tests, &mut binds);
                let cond = if tests.is_empty() {
                    "true".to_string()
                } else {
                    tests.join(" and ")
                };
                self.line(&format!("if {} then", cond));
                self.indent += 1;
                for (name, subj) in &binds {
                    self.line(&format!("local {} = {}", name, subj));
                }
                self.gen_block_to(then_block, dest);
                self.indent -= 1;
                match else_block.as_deref() {
                    Some(ElseBranch::Block(b)) => {
                        self.line("else");
                        self.indent += 1;
                        self.gen_block_to(b, dest);
                        self.indent -= 1;
                    }
                    Some(ElseBranch::If(inner)) => {
                        self.line("else");
                        self.indent += 1;
                        self.gen_expr_to(inner, dest);
                        self.indent -= 1;
                    }
                    None => {
                        if let Dest::Var(d) = dest {
                            self.line("else");
                            self.indent += 1;
                            self.line(&format!("{} = nil", d));
                            self.indent -= 1;
                        }
                    }
                }
                self.line("end");
            }
            ExprKind::Block(b) => self.gen_block_to(b, dest),
            ExprKind::Match { scrut, arms } => self.gen_match(scrut, arms, dest),
            ExprKind::Assign { target, value } => {
                let t = self.gen_inline(target);
                self.gen_expr_to(value, &Dest::Var(t));
                match dest {
                    Dest::Var(d) => self.line(&format!("{} = nil", d)),
                    Dest::Return => self.line("return nil"),
                    Dest::Discard => {}
                }
            }
            _ => {
                let v = self.gen_inline(e);
                match dest {
                    Dest::Discard => {
                        if matches!(
                            e.kind,
                            ExprKind::Call { .. } | ExprKind::MethodCall { .. } | ExprKind::MacroCall { .. }
                        ) {
                            self.line(&v);
                        }
                    }
                    Dest::Var(d) => self.line(&format!("{} = {}", d, v)),
                    Dest::Return => self.line(&format!("return {}", v)),
                }
            }
        }
    }

    // --- match -------------------------------------------------------------

    fn gen_match(&mut self, scrut: &Expr, arms: &[MatchArm], dest: &Dest) {
        let m = self.fresh_tmp();
        let s = self.gen_inline(scrut);
        self.line(&format!("local {} = {}", m, s));
        let done = format!("{}_done", m);
        self.line(&format!("local {} = false", done));

        for arm in arms {
            let (tests, binds) = self.arm_tests(arm, &m);
            self.line(&format!("if not {} then", done));
            self.indent += 1;

            let has_struct_test = !tests.is_empty();
            if has_struct_test {
                self.line(&format!("if {} then", tests.join(" and ")));
                self.indent += 1;
            }
            for (name, subj) in &binds {
                self.line(&format!("local {} = {}", name, subj));
            }
            let guard = arm.guard.as_ref().map(|g| self.gen_inline(g));
            if let Some(g) = &guard {
                self.line(&format!("if {} then", g));
                self.indent += 1;
            }

            self.gen_expr_to(&arm.body, dest);
            if !matches!(dest, Dest::Return) {
                self.line(&format!("{} = true", done));
            }

            if guard.is_some() {
                self.indent -= 1;
                self.line("end");
            }
            if has_struct_test {
                self.indent -= 1;
                self.line("end");
            }
            self.indent -= 1;
            self.line("end");
        }

        self.line(&format!("if not {} then", done));
        self.indent += 1;
        self.line("error(\"non-exhaustive match\")");
        self.indent -= 1;
        self.line("end");
    }

    /// Structural tests + bindings for a match arm against subject variable `m`.
    fn arm_tests(&mut self, arm: &MatchArm, m: &str) -> (Vec<String>, Vec<(String, String)>) {
        if arm.pats.len() == 1 {
            let mut tests = Vec::new();
            let mut binds = Vec::new();
            self.pat_test(&arm.pats[0], m, &mut tests, &mut binds);
            (tests, binds)
        } else {
            // or-patterns: combine alternatives; bindings are not supported here.
            let mut alts = Vec::new();
            for p in &arm.pats {
                let mut tests = Vec::new();
                let mut binds = Vec::new();
                self.pat_test(p, m, &mut tests, &mut binds);
                let cond = if tests.is_empty() {
                    "true".to_string()
                } else {
                    format!("({})", tests.join(" and "))
                };
                alts.push(cond);
            }
            (vec![alts.join(" or ")], Vec::new())
        }
    }

    fn pat_test(
        &mut self,
        pat: &Pattern,
        subject: &str,
        tests: &mut Vec<String>,
        binds: &mut Vec<(String, String)>,
    ) {
        match pat {
            Pattern::Wildcard => {}
            Pattern::Binding(name, _) => binds.push((name.clone(), subject.to_string())),
            Pattern::Literal(lit) => {
                let v = self.gen_inline(lit);
                tests.push(format!("{} == {}", subject, v));
            }
            Pattern::Range {
                lo,
                hi,
                inclusive,
            } => {
                let l = self.gen_inline(lo);
                let h = self.gen_inline(hi);
                let op = if *inclusive { "<=" } else { "<" };
                tests.push(format!("({0} >= {1} and {0} {2} {3})", subject, l, op, h));
            }
            Pattern::Path(segs) => {
                if segs.len() == 1 && segs[0] == "None" {
                    tests.push(format!("{} == nil", subject));
                } else if let Some((_, var, _)) = self.ctx.resolve_variant(segs) {
                    tests.push(format!("{}.tag == \"{}\"", subject, var));
                } else {
                    // best-effort: treat last segment as a tag
                    tests.push(format!("{}.tag == \"{}\"", subject, segs.last().unwrap()));
                }
            }
            Pattern::TupleVariant { path, elems } => {
                let head = path.last().map(String::as_str).unwrap_or("");
                match head {
                    "Some" => {
                        tests.push(format!("{} ~= nil", subject));
                        if let Some(inner) = elems.first() {
                            self.pat_test(inner, subject, tests, binds);
                        }
                    }
                    "Ok" => {
                        tests.push(format!("({0} ~= nil and {0}.err == nil)", subject));
                        if let Some(inner) = elems.first() {
                            let sub = format!("{}.ok", subject);
                            self.pat_test(inner, &sub, tests, binds);
                        }
                    }
                    "Err" => {
                        tests.push(format!("({0} ~= nil and {0}.err ~= nil)", subject));
                        if let Some(inner) = elems.first() {
                            let sub = format!("{}.err", subject);
                            self.pat_test(inner, &sub, tests, binds);
                        }
                    }
                    _ => {
                        if let Some((_, var, _)) = self.ctx.resolve_variant(path) {
                            tests.push(format!("{}.tag == \"{}\"", subject, var));
                        } else {
                            tests.push(format!("{}.tag == \"{}\"", subject, head));
                        }
                        for (i, elem) in elems.iter().enumerate() {
                            let sub = format!("{}[{}]", subject, i + 1);
                            self.pat_test(elem, &sub, tests, binds);
                        }
                    }
                }
            }
            Pattern::StructVariant { path, fields, .. } => {
                // If it resolves to an enum variant, test the tag; a plain struct
                // pattern needs no tag test.
                if let Some((_, var, _)) = self.ctx.resolve_variant(path) {
                    tests.push(format!("{}.tag == \"{}\"", subject, var));
                }
                for (fname, fpat) in fields {
                    let sub = format!("{}.{}", subject, fname);
                    self.pat_test(fpat, &sub, tests, binds);
                }
            }
        }
    }

    // --- inline (pure Lua expression, may hoist) --------------------------

    fn gen_inline(&mut self, e: &Expr) -> String {
        match &e.kind {
            ExprKind::Int(s) => lua_int_literal(s),
            ExprKind::Float(s) => s.replace('_', ""),
            ExprKind::Str(s) => s.clone(),
            ExprKind::Bool(b) => if *b { "true" } else { "false" }.to_string(),
            ExprKind::Path(segs) => self.gen_path(segs),
            ExprKind::Unary { op, expr } => {
                let inner = self.gen_inline(expr);
                match op {
                    UnOp::Neg => format!("-{}", paren_if_needed(&inner)),
                    UnOp::Not => format!("not {}", paren_if_needed(&inner)),
                }
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let l = self.gen_inline(lhs);
                let r = self.gen_inline(rhs);
                // `i64 / i64` and `i64 % i64` lower to `rt.idiv`/`rt.irem`, which
                // truncate toward zero to match Rust (Lua `//`/`%` floor, differing
                // when exactly one operand is negative: Rust `-7/2 == -3`,
                // `-7%2 == -1` vs Lua `-7//2 == -4`, `-7%2 == 1`).
                if *op == BinOp::Div && self.info.is_int_div(e.span.start, e.span.len) {
                    self.uses_rt = true;
                    return format!("rt.idiv({}, {})", l, r);
                }
                if *op == BinOp::Rem && self.info.is_int_rem(e.span.start, e.span.len) {
                    self.uses_rt = true;
                    return format!("rt.irem({}, {})", l, r);
                }
                // `String + String` is Lua concatenation, not arithmetic.
                if *op == BinOp::Add && self.info.is_str_concat(e.span.start, e.span.len) {
                    return format!("({} .. {})", l, r);
                }
                format!("({} {} {})", l, binop_lua(*op), r)
            }
            ExprKind::Call { callee, args } => self.gen_call(callee, args),
            ExprKind::MethodCall { recv, method, args, .. } => {
                let r = self.gen_inline(recv);
                let a: Vec<String> = args.iter().map(|x| self.gen_inline(x)).collect();
                // Recognized `String` methods route through `rt.str` (bracket
                // form avoids clashing with Lua keywords like `repeat`); the
                // receiver is passed as the first argument.
                if self.info.is_str_method(e.span.start, e.span.len) {
                    self.uses_rt = true;
                    let mut all = vec![r];
                    all.extend(a);
                    return format!("rt.str[\"{}\"]({})", method, all.join(", "));
                }
                format!("{}:{}({})", r, method, a.join(", "))
            }
            ExprKind::Field { base, name, .. } => {
                let b = self.gen_inline(base);
                format!("{}.{}", b, name)
            }
            ExprKind::Index { base, index } => {
                let b = self.gen_inline(base);
                let i = self.gen_inline(index);
                format!("{}[{}]", b, i)
            }
            ExprKind::MacroCall { name, args } => self.gen_macro(name, args),
            ExprKind::Range { start, end, .. } => {
                // Ranges are only meaningful as a `for` iterator; elsewhere they
                // have no first-class value.
                let _ = (start, end);
                "nil --[[ range only valid as a for-iterator ]]".to_string()
            }
            ExprKind::StructLit { path, fields } => self.gen_struct_lit(path, fields),
            ExprKind::Try { expr } => {
                let inner = self.gen_inline(expr);
                let r = self.fresh_tmp();
                self.line(&format!("local {} = {}", r, inner));
                // Propagate Err (docs §4.8). Option `?` needs the type checker.
                self.line(&format!("if {0} ~= nil and {0}.err ~= nil then return {0} end", r));
                format!("{}.ok", r)
            }
            // Control-flow in operand position: hoist into a temp.
            ExprKind::If { .. }
            | ExprKind::IfLet { .. }
            | ExprKind::Block(_)
            | ExprKind::Match { .. }
            | ExprKind::Assign { .. } => {
                let tmp = self.fresh_tmp();
                self.line(&format!("local {}", tmp));
                self.gen_expr_to(e, &Dest::Var(tmp.clone()));
                tmp
            }
        }
    }

    fn gen_path(&mut self, segs: &[String]) -> String {
        if segs.len() == 1 && segs[0] == "None" {
            return "nil".to_string();
        }
        if let Some((en, var, shape)) = self.ctx.resolve_variant(segs) {
            if let VarShape::Unit = shape {
                let meta = enum_ref(segs, &en);
                return format!("setmetatable({{ tag = \"{}\" }}, {})", var, meta);
            }
        }
        segs.join(".")
    }

    fn gen_call(&mut self, callee: &Expr, args: &[Expr]) -> String {
        if let ExprKind::Path(segs) = &callee.kind {
            let head = segs.last().cloned().unwrap_or_default();
            // Option / Result built-ins.
            if segs.len() == 1 {
                match head.as_str() {
                    "Some" => return self.gen_inline(&args[0]),
                    "Ok" => {
                        let v = self.gen_inline(&args[0]);
                        return format!("{{ ok = {} }}", v);
                    }
                    "Err" => {
                        let v = self.gen_inline(&args[0]);
                        return format!("{{ err = {} }}", v);
                    }
                    _ => {}
                }
            }
            // Collection constructors.
            if segs.len() == 2 {
                match (segs[0].as_str(), segs[1].as_str()) {
                    ("HashMap", "new") => {
                        self.uses_rt = true;
                        return "rt.map()".to_string();
                    }
                    ("Vec", "new") => {
                        self.uses_rt = true;
                        return "rt.vec({ n = 0 })".to_string();
                    }
                    _ => {}
                }
            }
            // Enum tuple-variant construction.
            if let Some((en, var, VarShape::Tuple)) = self.ctx.resolve_variant(segs) {
                let a: Vec<String> = args.iter().map(|x| self.gen_inline(x)).collect();
                let meta = enum_ref(segs, &en);
                let mut parts = vec![format!("tag = \"{}\"", var)];
                parts.extend(a);
                return format!("setmetatable({{ {} }}, {})", parts.join(", "), meta);
            }
            // Associated function `Type::func(..)` or plain call.
            let a: Vec<String> = args.iter().map(|x| self.gen_inline(x)).collect();
            return format!("{}({})", segs.join("."), a.join(", "));
        }
        let c = self.gen_inline(callee);
        let a: Vec<String> = args.iter().map(|x| self.gen_inline(x)).collect();
        format!("{}({})", c, a.join(", "))
    }

    fn gen_macro(&mut self, name: &str, args: &[Expr]) -> String {
        let a: Vec<String> = args.iter().map(|x| self.gen_inline(x)).collect();
        match name {
            "vec" => {
                self.uses_rt = true;
                // 0-based storage + length field, matching Rust indexing.
                let mut parts: Vec<String> = a
                    .iter()
                    .enumerate()
                    .map(|(i, v)| format!("[{}] = {}", i, v))
                    .collect();
                parts.push(format!("n = {}", a.len()));
                format!("rt.vec({{ {} }})", parts.join(", "))
            }
            "format" => {
                self.uses_rt = true;
                format!("rt.format({})", a.join(", "))
            }
            "println" => {
                self.uses_rt = true;
                format!("rt.println({})", a.join(", "))
            }
            "print" => {
                self.uses_rt = true;
                format!("rt.print({})", a.join(", "))
            }
            "panic" => {
                self.uses_rt = true;
                format!("rt.panic(rt.format({}))", a.join(", "))
            }
            other => {
                // Unknown macro: best-effort passthrough as a call.
                format!("{}({})", other, a.join(", "))
            }
        }
    }

    fn gen_struct_lit(&mut self, path: &[String], fields: &[(String, Expr)]) -> String {
        let field_parts: Vec<String> = fields
            .iter()
            .map(|(n, e)| {
                let v = self.gen_inline(e);
                format!("{} = {}", n, v)
            })
            .collect();

        // Struct variant of an enum?
        if let Some((en, var, VarShape::Struct)) = self.ctx.resolve_variant(path) {
            let meta = enum_ref(path, &en);
            let mut parts = vec![format!("tag = \"{}\"", var)];
            parts.extend(field_parts);
            return format!("setmetatable({{ {} }}, {})", parts.join(", "), meta);
        }

        let name = path.last().cloned().unwrap_or_default();
        if self.ctx.structs.contains(&name) {
            // Cross-module `mod::Type { .. }` uses the qualified class table.
            let meta = if path.len() > 1 {
                path.join(".")
            } else {
                name.clone()
            };
            format!("setmetatable({{ {} }}, {})", field_parts.join(", "), meta)
        } else {
            format!("{{ {} }}", field_parts.join(", "))
        }
    }
}

/// Collect trait declarations across all scopes (root + nested modules), keyed
/// by simple name.
fn collect_traits<'p>(items: &'p [Item], out: &mut HashMap<&'p str, &'p TraitDecl>) {
    for it in items {
        match it {
            Item::Trait(t) => {
                out.insert(t.name.as_str(), t);
            }
            Item::Mod(m) => collect_traits(&m.items, out),
            _ => {}
        }
    }
}

/// Lua expression for the enum class table referenced by a variant path.
/// `["math","Shape","Circle"]` -> `math.Shape`; a bare `["Circle"]` uses the
/// resolved owning enum's (simple) name, which is a same-scope local.
fn enum_ref(segs: &[String], en_simple: &str) -> String {
    if segs.len() >= 2 {
        segs[..segs.len() - 1].join(".")
    } else {
        en_simple.to_string()
    }
}

/// If `impl <trait> for T` defines the operator method `method`, return the Lua
/// metamethod name to alias it to (enabling `a + b`, `a == b`, etc.).
fn op_alias(trait_name: &str, method: &str) -> Option<&'static str> {
    Some(match (trait_name, method) {
        ("Add", "add") => "__add",
        ("Sub", "sub") => "__sub",
        ("Mul", "mul") => "__mul",
        ("Div", "div") => "__div",
        ("Rem", "rem") => "__mod",
        ("Neg", "neg") => "__unm",
        ("PartialEq", "eq") | ("Eq", "eq") => "__eq",
        _ => return None,
    })
}

fn needs_hoist(e: &Expr) -> bool {
    matches!(
        e.kind,
        ExprKind::If { .. } | ExprKind::IfLet { .. } | ExprKind::Block(_) | ExprKind::Match { .. }
    )
}

fn binop_lua(op: BinOp) -> &'static str {
    // `/` maps to Lua float division; integer-vs-float selection needs the type
    // checker (docs §9 open question 6). This MVP always emits `/`.
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Rem => "%",
        BinOp::Eq => "==",
        BinOp::Ne => "~=",
        BinOp::Lt => "<",
        BinOp::Le => "<=",
        BinOp::Gt => ">",
        BinOp::Ge => ">=",
        BinOp::And => "and",
        BinOp::Or => "or",
    }
}

fn lua_int_literal(s: &str) -> String {
    let clean = s.replace('_', "");
    if let Some(bits) = clean.strip_prefix("0b").or_else(|| clean.strip_prefix("0B")) {
        if let Ok(v) = i64::from_str_radix(bits, 2) {
            return v.to_string();
        }
    }
    clean
}

fn paren_if_needed(s: &str) -> String {
    let is_atom = !s.contains(' ')
        || (s.starts_with('(') && s.ends_with(')'))
        || s.chars().all(|c| c.is_alphanumeric() || c == '_' || c == '.');
    if is_atom {
        s.to_string()
    } else {
        format!("({})", s)
    }
}
