//! Lua 5.5 source backend.
//!
//! Expression-to-statement lowering uses a "destination" model (docs §4.1):
//! every expression is generated *to* a `Dest` (discard / assign / return).
//! Control-flow expressions push the same `Dest` into their branches; only
//! value-producing control-flow in operand position hoists a temporary.
//!
//! Data mapping (docs §4.2 / §4.3):
//!   struct        -> table + metatable (methods in `__index`)
//!   enum variant  -> { tag = "Name", ... } + metatable
//!   Option        -> pure nil: Some(v) => v, None => nil
//!   Result        -> first-class tagged runtime value

use rua_core::{BuiltinMacroLowering, builtin_macro_by_id};

use crate::ast::*;
use crate::backend_layout::BackendLayout;
use crate::lua_ir::{
    BinaryOp as LuaBinaryOp, Expr as LuaExpr, FunctionTarget, InlineStatement, TableField,
    UnaryOp as LuaUnaryOp,
};
use crate::typeck::{IterAdapterKind, IterConsumerKind, IterPlan, IterSourceKind, TypeInfo};
use std::collections::{HashMap, HashSet};

#[derive(Clone)]
enum Dest {
    Discard,
    Var(LuaExpr),
    Return,
}

struct IterCall<'a> {
    kind: IterAdapterKind,
    args: &'a [Expr],
}

struct IterChain<'a> {
    source: &'a Expr,
    adapters: Vec<IterCall<'a>>,
    consumer_args: &'a [Expr],
}

#[derive(Default)]
struct IterAdapterState {
    counter: Option<String>,
    limit: Option<String>,
}

enum IterLoopSource {
    Range {
        start: String,
        end: String,
        inclusive: bool,
    },
    Vec {
        holder: String,
    },
}

pub fn generate(
    program: &crate::typed_ir::TypedProgram,
    rules: &crate::builtins::CodegenRules,
) -> String {
    generate_with_source_map(program, rules).source
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct LuaSourceMapping {
    pub generated_start: usize,
    pub generated_end: usize,
    pub source: crate::token::SourceRange,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedLua {
    pub source: String,
    pub source_map: Vec<LuaSourceMapping>,
}

pub fn generate_with_source_map(
    program: &crate::typed_ir::TypedProgram,
    rules: &crate::builtins::CodegenRules,
) -> GeneratedLua {
    let hir = program.hir();
    let mut cg = Codegen {
        lua: crate::lua_ir::Builder::new(),
        uses_rt: false,
        closure_return_targets: Vec::new(),
        program,
        info: program.types(),
        hir,
        layout: BackendLayout::new(program),
        current_module: hir.root,
        builtin_rules: rules,
    };
    cg.gen_program(program.syntax());

    let mut prefix = String::from("-- Generated by ruac (Rua -> Lua 5.5). Do not edit by hand.\n");
    if cg.uses_rt {
        prefix.push_str("local rt = require(\"rua_rt\")\n");
        prefix.push_str(&format!(
            "assert(rt.ABI_VERSION == {}, \"incompatible rua_rt ABI\")\n",
            rua_core::RUNTIME_ABI_VERSION
        ));
    }
    let printed = crate::lua_ir::print_with_source_map(&cg.lua.finish());
    let generated_offset = prefix.len();
    let source_map = printed
        .mappings
        .into_iter()
        .map(|mapping| LuaSourceMapping {
            generated_start: generated_offset + mapping.generated_start,
            generated_end: generated_offset + mapping.generated_end,
            source: mapping.source,
        })
        .collect();
    prefix.push_str(&printed.source);
    GeneratedLua {
        source: prefix,
        source_map,
    }
}

struct Codegen<'a> {
    lua: crate::lua_ir::Builder,
    /// Set when any generated code references the `rua_rt` runtime shim.
    uses_rt: bool,
    /// Inlined iterator closure returns assign a local and jump out of the
    /// closure body instead of returning from the enclosing Rua function.
    closure_return_targets: Vec<(String, String)>,
    program: &'a crate::typed_ir::TypedProgram,
    info: &'a TypeInfo,
    hir: &'a crate::hir::ResolvedHir,
    layout: BackendLayout,
    current_module: crate::hir::ModuleId,
    builtin_rules: &'a crate::builtins::CodegenRules,
}

fn statement_source(statement: &Stmt) -> Option<crate::token::SourceRange> {
    match statement {
        Stmt::Let { name_span, .. } => Some(*name_span),
        Stmt::Expr(expression) => Some(expression.span),
        Stmt::Return(Some(expression)) => Some(expression.span),
        Stmt::While { cond, .. } => Some(cond.span),
        Stmt::For { var_span, .. } => Some(*var_span),
        Stmt::WhileLet { expr, .. } => Some(expr.span),
        Stmt::Return(None) | Stmt::Loop { .. } | Stmt::Break | Stmt::Continue => None,
    }
}

// ---------------------------------------------------------------------------
// EmmyLua helpers — convert rua types to LuaLS annotations
// ---------------------------------------------------------------------------

fn type_to_emmylua(ty: &Type) -> String {
    match ty {
        Type::Path { name, args, .. } => {
            let base = match name.as_str() {
                "i64" | "i8" | "i16" | "i32" | "isize" | "u8" | "u16" | "u32" | "u64" | "usize" => {
                    "integer"
                }
                "f64" | "f32" => "number",
                "bool" => "boolean",
                "String" | "str" => "string",
                "Vec" => {
                    if let Some(a) = args.first() {
                        return format!("{}[]", type_to_emmylua(a));
                    }
                    "table"
                }
                "Option" => {
                    if let Some(a) = args.first() {
                        return format!("{}|nil", type_to_emmylua(a));
                    }
                    "any|nil"
                }
                "Result" => "table",
                "HashMap" => "table",
                _ => name.as_str(),
            };
            base.to_string()
        }
        Type::Ref { inner, .. } => type_to_emmylua(inner),
        Type::Function { params, ret } => {
            let params = params.iter().map(type_to_emmylua).collect::<Vec<_>>();
            format!("fun({}): {}", params.join(", "), type_to_emmylua(ret))
        }
        Type::Tuple(items) => format!(
            "[{}]",
            items
                .iter()
                .map(type_to_emmylua)
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Type::Unit => "nil".into(),
    }
}

impl Codegen<'_> {
    fn emit_struct_annotation(&mut self, s: &StructDecl) {
        self.annotation(format!("---@class {}", s.name));
        if !s.generics.is_empty() {
            let gens: Vec<&str> = s.generics.iter().map(|g| g.name.as_str()).collect();
            self.annotation(format!("---@generic {}", gens.join(", ")));
        }
    }

    fn emit_fn_annotation(&mut self, f: &FnDecl) {
        if !f.generics.is_empty() {
            let gens: Vec<&str> = f.generics.iter().map(|g| g.name.as_str()).collect();
            self.annotation(format!("---@generic {}", gens.join(", ")));
        }
        // Parameter types are explicit in Rua source; only emit the return
        // annotation so LuaLS can infer the result type at call sites.
        if let Some(ret) = &f.ret {
            self.annotation(format!("---@return {}", type_to_emmylua(ret)));
        }
    }

    fn block_has_continue(block: &Block) -> bool {
        for s in &block.stmts {
            if matches!(s, Stmt::Continue) {
                return true;
            }
            match s {
                Stmt::While { body, .. }
                | Stmt::Loop { body }
                | Stmt::WhileLet { body, .. }
                | Stmt::For { body, .. } => {
                    if Self::block_has_continue(body) {
                        return true;
                    }
                }
                Stmt::Expr(e) if Self::expr_has_continue(e) => {
                    return true;
                }
                _ => {}
            }
        }
        false
    }

    fn expr_has_continue(expr: &Expr) -> bool {
        match &expr.kind {
            ExprKind::Block(b) => Self::block_has_continue(b),
            ExprKind::If {
                then_block,
                else_block,
                ..
            } => {
                Self::block_has_continue(then_block)
                    || else_block.as_ref().is_some_and(|eb| match eb.as_ref() {
                        ElseBranch::Block(b) => Self::block_has_continue(b),
                        ElseBranch::If(e) => Self::expr_has_continue(e),
                    })
            }
            ExprKind::Match { arms, .. } => arms.iter().any(|a| Self::expr_has_continue(&a.body)),
            _ => false,
        }
    }

    fn annotation(&mut self, source: impl Into<String>) {
        self.lua.annotation(source);
    }

    fn local(&mut self, name: impl Into<String>, value: Option<LuaExpr>) {
        self.lua
            .local(vec![name.into()], value.into_iter().collect());
    }

    fn locals(&mut self, names: Vec<String>) {
        self.lua.local(names, Vec::new());
    }

    fn assign(&mut self, target: LuaExpr, value: LuaExpr) {
        self.lua.assign(target, value);
    }

    fn return_value(&mut self, value: LuaExpr) {
        self.lua.return_values(vec![value]);
    }

    fn return_none(&mut self) {
        self.lua.return_values(Vec::new());
    }

    fn expression_statement(&mut self, expression: LuaExpr) {
        self.lua.expression(expression);
    }

    fn blank(&mut self) {
        self.lua.blank();
    }

    fn fresh_tmp(&mut self) -> String {
        self.layout.fresh_temporary()
    }

    fn local_name(&self, name: &str) -> String {
        self.layout.local_name(self.current_module, name)
    }

    // --- program ----------------------------------------------------------

    fn gen_program(&mut self, prog: &Program) {
        if prog.is_decl {
            return;
        }
        // Every root callable gets exactly one lexical binding. Definitions
        // below assign to these bindings, which makes forward and mutual
        // recursion identical and avoids `local function` shadowing.
        let fn_names: Vec<String> = prog
            .items
            .iter()
            .enumerate()
            .filter_map(|(item_index, item)| match item {
                Item::Fn(_) => self
                    .layout
                    .definition(self.program.item_definition(self.hir.root, item_index))
                    .map(ToString::to_string),
                _ => None,
            })
            .collect();
        if !fn_names.is_empty() {
            self.locals(fn_names);
        }

        // Class tables (with `__index`) for structs and enums so their values
        // can carry methods. Each is self-contained: @class annotation + local table.
        for (item_index, item) in prog.items.iter().enumerate() {
            match item {
                Item::Struct(s) => {
                    let definition = self.program.item_definition(self.hir.root, item_index);
                    let place = self.layout.definition(definition).unwrap().clone();
                    self.emit_struct_annotation(s);
                    for field in &s.fields {
                        self.annotation(format!(
                            "---@field {} {}",
                            field.name,
                            type_to_emmylua(&field.ty)
                        ));
                    }
                    self.lua.local_table(place.to_string());
                    self.assign(place.field("__index").expression(), place.expression());
                }
                Item::Enum(e) => {
                    let definition = self.program.item_definition(self.hir.root, item_index);
                    let place = self.layout.definition(definition).unwrap().clone();
                    self.annotation(format!("---@class {0}", e.name));
                    self.lua.local_table(place.to_string());
                    self.assign(place.field("__index").expression(), place.expression());
                }
                _ => {}
            }
        }

        // Trait table across all scopes (root + modules), keyed by simple name,
        // for resolving inherited default methods in `impl Trait for Type`.
        let mut traits = HashMap::new();
        collect_traits(&prog.items, self.hir.root, self.program, &mut traits);

        // Phase 1: allocate every module/type table.
        for (item_index, item) in prog.items.iter().enumerate() {
            if let Item::Mod(m) = item
                && !m.is_decl
            {
                let module = self.program.child_module(self.hir.root, item_index);
                self.declare_mod(m, module);
            }
        }
        // Nested extern places live under their owning module table, so all
        // runtime module places must exist before extern bindings are emitted.
        self.bind_externs(&prog.items, self.hir.root);
        // Phase 2: define every callable against its preallocated place.
        for (item_index, item) in prog.items.iter().enumerate() {
            if let Item::Mod(m) = item
                && !m.is_decl
            {
                let module = self.program.child_module(self.hir.root, item_index);
                self.define_mod(m, &traits, module);
                self.publish_mod(m, module);
            }
        }
        for (item_index, item) in prog.items.iter().enumerate() {
            if let Item::Fn(f) = item {
                let definition = self.program.item_definition(self.hir.root, item_index);
                self.gen_free_fn(f, definition);
            }
        }
        self.gen_impls(&prog.items, &traits, self.hir.root);
        // Phase 3: execute initializers in observable source order.
        self.init_entries(&prog.source_order, &prog.items, &prog.chunk, self.hir.root);

        // Export every public runtime item after chunk initialization.
        let exports: Vec<(String, LuaExpr)> = prog
            .items
            .iter()
            .enumerate()
            .filter_map(|(item_index, item)| match item {
                Item::Fn(f) if f.is_pub => self
                    .layout
                    .definition(self.program.item_definition(self.hir.root, item_index))
                    .map(|place| (f.name.clone(), place.expression())),
                Item::Struct(s) if s.is_pub => self
                    .layout
                    .definition(self.program.item_definition(self.hir.root, item_index))
                    .map(|place| (s.name.clone(), place.expression())),
                Item::Enum(e) if e.is_pub => self
                    .layout
                    .definition(self.program.item_definition(self.hir.root, item_index))
                    .map(|place| (e.name.clone(), place.expression())),
                Item::Mod(m) if m.is_pub && !m.is_decl => self
                    .layout
                    .module(self.program.child_module(self.hir.root, item_index))
                    .map(|place| (m.name.clone(), place.expression())),
                _ => None,
            })
            .collect();
        if !exports.is_empty() {
            self.blank();
            self.lua.return_table(exports);
        }
    }

    fn bind_externs(&mut self, items: &[Item], module: crate::hir::ModuleId) {
        let previous_module = self.current_module;
        self.current_module = module;
        for (item_index, item) in items.iter().enumerate() {
            match item {
                Item::Extern(block) => {
                    for (function_index, function) in block.fns.iter().enumerate() {
                        let definition =
                            self.program
                                .extern_function(module, item_index, function_index);
                        if block.abi == "lua-result" {
                            self.bind_result_extern(function, definition);
                        } else {
                            self.bind_plain_extern(function, definition);
                        }
                    }
                }
                Item::Mod(child) if !child.is_decl => {
                    let child_module = self.program.child_module(module, item_index);
                    self.bind_externs(&child.items, child_module);
                }
                _ => {}
            }
        }
        self.current_module = previous_module;
    }

    fn bind_plain_extern(&mut self, function: &ExternFn, definition: crate::hir::DefId) {
        let place = self.layout.definition(definition).unwrap().clone();
        let ambient = LuaExpr::name("_G").index(LuaExpr::string(&function.name));
        let missing = LuaExpr::string(&format!("missing Lua extern `{}`", function.name));
        self.local(
            place.to_string(),
            Some(LuaExpr::name("assert").call(vec![ambient, missing])),
        );
    }

    fn bind_result_extern(&mut self, function: &ExternFn, definition: crate::hir::DefId) {
        self.uses_rt = true;
        self.lua.push_anchor(function.name_span);
        let host = self.fresh_tmp();
        let ambient = LuaExpr::name("_G").index(LuaExpr::string(&function.name));
        let missing = LuaExpr::string(&format!("missing Lua extern `{}`", function.name));
        self.local(
            &host,
            Some(LuaExpr::name("assert").call(vec![ambient, missing])),
        );

        let params = function
            .params
            .iter()
            .map(|parameter| self.local_name(&parameter.name))
            .collect::<Vec<_>>();
        self.lua.begin_function(
            self.layout.callable_target(definition, false),
            params.clone(),
        );
        let mut host_args = Vec::new();
        for (parameter, parameter_name) in function.params.iter().zip(params) {
            if self
                .hir
                .type_is_builtin(&parameter.ty, rua_core::BuiltinId::TypeResult)
            {
                let ok = self.fresh_tmp();
                let error = self.fresh_tmp();
                self.lua.local(vec![ok.clone(), error.clone()], Vec::new());
                self.lua.begin_if(
                    LuaExpr::name(&parameter_name)
                        .field("tag")
                        .binary(LuaBinaryOp::Eq, LuaExpr::string("ok")),
                );
                self.assign(
                    LuaExpr::name(&ok),
                    LuaExpr::name(&parameter_name).field("value"),
                );
                self.lua.begin_else();
                self.assign(
                    LuaExpr::name(&error),
                    LuaExpr::name(&parameter_name).field("value"),
                );
                self.lua.end_block();
                host_args.extend([LuaExpr::name(ok), LuaExpr::name(error)]);
            } else {
                host_args.push(LuaExpr::name(parameter_name));
            }
        }

        let value = self.fresh_tmp();
        let error = self.fresh_tmp();
        self.lua.local(
            vec![value.clone(), error.clone()],
            vec![LuaExpr::name(host).call(host_args)],
        );
        self.lua
            .begin_if(LuaExpr::name(&error).binary(LuaBinaryOp::Ne, LuaExpr::Nil));
        self.lua
            .return_values(vec![rt_call("result_err", vec![LuaExpr::name(&error)])]);
        self.lua.end_block();
        self.lua
            .return_values(vec![rt_call("result_ok", vec![LuaExpr::name(&value)])]);
        self.lua.end_block();
        self.lua.pop_anchor();
    }

    fn declare_mod(&mut self, m: &ModDecl, module: crate::hir::ModuleId) {
        let place = self
            .layout
            .module(module)
            .expect("runtime module has a backend place")
            .clone();
        self.blank();
        self.annotation(format!("---@class {place}"));
        if self.hir.module(module).parent == Some(self.hir.root) {
            self.lua.local_table(place.to_string());
        } else {
            self.lua.assign_table(place.expression());
        }

        // Class tables for module-local structs/enums.
        for (item_index, item) in m.items.iter().enumerate() {
            match item {
                Item::Struct(_) => {
                    let definition = self.program.item_definition(module, item_index);
                    let type_place = self.layout.definition(definition).unwrap().clone();
                    self.lua.assign_table(type_place.expression());
                    self.assign(
                        type_place.field("__index").expression(),
                        type_place.expression(),
                    );
                }
                Item::Enum(_) => {
                    let definition = self.program.item_definition(module, item_index);
                    let type_place = self.layout.definition(definition).unwrap().clone();
                    self.lua.assign_table(type_place.expression());
                    self.assign(
                        type_place.field("__index").expression(),
                        type_place.expression(),
                    );
                }
                _ => {}
            }
        }

        for (item_index, item) in m.items.iter().enumerate() {
            if let Item::Mod(child) = item
                && !child.is_decl
            {
                let child_module = self.program.child_module(module, item_index);
                self.declare_mod(child, child_module);
            }
        }
    }

    fn define_mod(
        &mut self,
        m: &ModDecl,
        traits: &HashMap<crate::hir::DefId, &TraitDecl>,
        module: crate::hir::ModuleId,
    ) {
        let previous_module = self.current_module;
        self.current_module = module;
        for (item_index, item) in m.items.iter().enumerate() {
            match item {
                Item::Fn(f) => {
                    let definition = self.program.item_definition(module, item_index);
                    let place = self.layout.definition(definition).unwrap().clone();
                    self.lua.push_anchor(f.name_span);
                    self.blank();
                    self.emit_fn_annotation(f);
                    let params = f
                        .params
                        .iter()
                        .map(|parameter| self.local_name(&parameter.name))
                        .collect();
                    self.lua.begin_function(place.function_target(), params);
                    self.gen_block_to(&f.body, &Dest::Return);
                    self.lua.end_block();
                    self.lua.pop_anchor();
                }
                Item::Mod(md) if !md.is_decl => {
                    let child = self.program.child_module(module, item_index);
                    self.define_mod(md, traits, child);
                }
                _ => {}
            }
        }
        self.gen_impls(&m.items, traits, module);
        self.current_module = previous_module;
    }

    fn init_entries(
        &mut self,
        order: &[ChunkEntry],
        items: &[Item],
        chunk: &Block,
        module: crate::hir::ModuleId,
    ) {
        let previous_module = self.current_module;
        self.current_module = module;
        for entry in order {
            match *entry {
                ChunkEntry::Statement(index) => self.gen_stmt(&chunk.stmts[index]),
                ChunkEntry::Item(index) => {
                    if let Item::Mod(child_decl) = &items[index]
                        && !child_decl.is_decl
                    {
                        let child = self.program.child_module(module, index);
                        self.init_entries(
                            &child_decl.source_order,
                            &child_decl.items,
                            &child_decl.chunk,
                            child,
                        );
                    }
                }
            }
        }
        self.current_module = previous_module;
    }

    fn publish_mod(&mut self, declaration: &ModDecl, module: crate::hir::ModuleId) {
        let module_place = self.layout.module(module).unwrap().clone();
        for (item_index, item) in declaration.items.iter().enumerate() {
            let exported = match item {
                Item::Fn(function) if function.is_pub => self
                    .layout
                    .definition(self.program.item_definition(module, item_index))
                    .map(|place| (function.name.as_str(), place.clone())),
                Item::Struct(structure) if structure.is_pub => self
                    .layout
                    .definition(self.program.item_definition(module, item_index))
                    .map(|place| (structure.name.as_str(), place.clone())),
                Item::Enum(enumeration) if enumeration.is_pub => self
                    .layout
                    .definition(self.program.item_definition(module, item_index))
                    .map(|place| (enumeration.name.as_str(), place.clone())),
                Item::Mod(child) if child.is_pub && !child.is_decl => self
                    .layout
                    .module(self.program.child_module(module, item_index))
                    .map(|place| (child.name.as_str(), place.clone())),
                _ => None,
            };
            if let Some((name, place)) = exported {
                let encoded = self.layout.member_name(name);
                let canonical = module_place.field(&encoded);
                if place != canonical || encoded != name {
                    self.assign(
                        module_place.expression().index(LuaExpr::string(name)),
                        place.expression(),
                    );
                }
            }
            if let Item::Mod(child) = item
                && !child.is_decl
            {
                let child_module = self.program.child_module(module, item_index);
                self.publish_mod(child, child_module);
            }
        }
    }

    /// Emit all `impl` blocks in `items` (methods, operator aliases, inherited
    /// trait defaults). The type's class table is a same-scope local, so
    /// `function Type.method(...)` binds correctly at root or inside a module.
    fn gen_impls(
        &mut self,
        items: &[Item],
        traits: &HashMap<crate::hir::DefId, &TraitDecl>,
        module: crate::hir::ModuleId,
    ) {
        let previous_module = self.current_module;
        self.current_module = module;
        for (item_index, item) in items.iter().enumerate() {
            if let Item::Impl(im) = item {
                let implementation = self.program.implementation(module, item_index);
                let type_place = self
                    .target_place(crate::hir::ResolvedTarget::Item(implementation.owner))
                    .expect("resolved impl owner has a backend place");
                let mut overridden = HashSet::new();
                for (method_index, m) in im.methods.iter().enumerate() {
                    let definition =
                        self.program
                            .implementation_method(module, item_index, method_index);
                    if let Some(origin) = self
                        .hir
                        .trait_method_implementations
                        .get(&definition)
                        .copied()
                    {
                        overridden.insert(origin);
                    }
                    self.gen_method(m, definition);
                    if let Some(trait_target) = self.hir.method_traits.get(&definition).copied()
                        && let Some(meta) = op_alias(trait_target, &m.name)
                    {
                        let source = self
                            .layout
                            .definition(definition)
                            .expect("typed method has a backend place")
                            .expression();
                        self.assign(type_place.field(meta).expression(), source);
                    }
                }
                if let Some(crate::hir::TraitTarget::Item(trait_id)) = implementation.trait_target
                    && let Some(td) = traits.get(&trait_id)
                {
                    for (method_index, tm) in td.methods.iter().enumerate() {
                        let origin = self.program.trait_method(trait_id, method_index);
                        if tm.default.is_some() && !overridden.contains(&origin) {
                            let definition =
                                self.program.inherited_method(implementation.owner, origin);
                            self.gen_trait_default(tm, definition);
                            let meta = self
                                .hir
                                .method_traits
                                .get(&definition)
                                .copied()
                                .and_then(|trait_target| op_alias(trait_target, &tm.name));
                            if let Some(meta) = meta {
                                let source = self
                                    .layout
                                    .definition(definition)
                                    .expect("inherited method has a backend place")
                                    .expression();
                                self.assign(type_place.field(meta).expression(), source);
                            }
                        }
                    }
                }
            }
        }
        self.current_module = previous_module;
    }

    fn gen_free_fn(&mut self, f: &FnDecl, definition: crate::hir::DefId) {
        self.lua.push_anchor(f.name_span);
        self.blank();
        self.emit_fn_annotation(f);
        let params = f
            .params
            .iter()
            .map(|parameter| self.local_name(&parameter.name))
            .collect();
        let place = self.layout.definition(definition).unwrap().clone();
        self.lua.begin_function(place.function_target(), params);
        self.gen_block_to(&f.body, &Dest::Return);
        self.lua.end_block();
        self.lua.pop_anchor();
    }

    fn gen_method(&mut self, m: &FnDecl, definition: crate::hir::DefId) {
        self.lua.push_anchor(m.name_span);
        self.blank();
        // Return annotation so LuaLS can infer result types.
        if let Some(ret) = &m.ret {
            self.annotation(format!("---@return {}", type_to_emmylua(ret)));
        }
        let params = m
            .params
            .iter()
            .map(|parameter| self.local_name(&parameter.name))
            .collect();
        let target = self.layout.callable_target(definition, m.has_self);
        self.lua.begin_function(target, params);
        self.gen_block_to(&m.body, &Dest::Return);
        self.lua.end_block();
        self.lua.pop_anchor();
    }

    fn gen_trait_default(&mut self, tm: &TraitMethod, definition: crate::hir::DefId) {
        self.lua.push_anchor(tm.name_span);
        self.blank();
        // Emit param/return annotations
        let skip_self = if tm.has_self { 1 } else { 0 };
        for p in tm.params.iter().skip(skip_self) {
            self.annotation(format!("---@param {} {}", p.name, type_to_emmylua(&p.ty)));
        }
        if let Some(ret) = &tm.ret {
            self.annotation(format!("---@return {}", type_to_emmylua(ret)));
        }
        let params = tm
            .params
            .iter()
            .map(|parameter| self.local_name(&parameter.name))
            .collect();
        let target = self.layout.callable_target(definition, tm.has_self);
        self.lua.begin_function(target, params);
        // `default` is guaranteed Some by the caller.
        if let Some(body) = &tm.default {
            self.gen_block_to(body, &Dest::Return);
        }
        self.lua.end_block();
        self.lua.pop_anchor();
    }

    // --- statements --------------------------------------------------------

    fn gen_stmt(&mut self, statement: &Stmt) {
        let anchor = statement_source(statement);
        if let Some(source) = anchor {
            self.lua.push_anchor(source);
        }
        self.gen_stmt_inner(statement);
        if anchor.is_some() {
            self.lua.pop_anchor();
        }
    }

    fn gen_stmt_inner(&mut self, s: &Stmt) {
        match s {
            Stmt::Let { name, init, ty, .. } => {
                let local = self.local_name(name);
                // EmmyLua type annotation for explicitly typed bindings
                if let Some(ty_ann) = ty {
                    self.annotation(format!("---@type {}", type_to_emmylua(ty_ann)));
                }
                if let ExprKind::Closure { params, body, .. } = &init.kind {
                    self.gen_closure_local(&local, params, body);
                } else if let ExprKind::Try { expr } = &init.kind {
                    let v = self.gen_inline(expr);
                    if self.info.is_result_try(init.id) {
                        let result = self.fresh_tmp();
                        self.local(&result, Some(v));
                        self.lua.compact_if(
                            LuaExpr::name(&result)
                                .field("tag")
                                .binary(LuaBinaryOp::Eq, LuaExpr::string("err")),
                            vec![InlineStatement::return_value(LuaExpr::name(&result))],
                        );
                        self.local(&local, Some(LuaExpr::name(&result).field("value")));
                    } else {
                        self.local(&local, Some(v));
                        self.lua.compact_if(
                            LuaExpr::name(&local).binary(LuaBinaryOp::Eq, LuaExpr::Nil),
                            vec![InlineStatement::return_nil()],
                        );
                    }
                } else if self.info.iter_plan(init.id).is_some() || needs_hoist(init) {
                    self.local(&local, None);
                    self.gen_expr_to(init, &Dest::Var(LuaExpr::name(local)));
                } else {
                    let v = self.gen_inline(init);
                    self.local(&local, Some(v));
                }
            }
            Stmt::Expr(e) => self.gen_expr_to(e, &Dest::Discard),
            Stmt::Return(opt) => {
                if let Some((target, label)) = self.closure_return_targets.last().cloned() {
                    match opt {
                        Some(e) => self.gen_expr_to(e, &Dest::Var(LuaExpr::name(&target))),
                        None => self.assign(LuaExpr::name(target), LuaExpr::Nil),
                    }
                    self.lua.goto(label);
                    return;
                }
                self.lua.begin_do();
                match opt {
                    Some(e) => self.gen_expr_to(e, &Dest::Return),
                    None => self.return_none(),
                }
                self.lua.end_block();
            }
            Stmt::While { cond, body } => {
                let c = self.gen_inline(cond);
                self.lua.begin_while(c);
                self.gen_block_to(body, &Dest::Discard);
                if Self::block_has_continue(body) {
                    self.lua.label("continue");
                }
                self.lua.end_block();
            }
            Stmt::Loop { body } => {
                self.lua.begin_while(LuaExpr::Bool(true));
                self.gen_block_to(body, &Dest::Discard);
                if Self::block_has_continue(body) {
                    self.lua.label("continue");
                }
                self.lua.end_block();
            }
            Stmt::For {
                var, iter, body, ..
            } => self.gen_for(var, iter, body),
            Stmt::WhileLet { pat, expr, body } => {
                self.lua.begin_while(LuaExpr::Bool(true));
                let m = self.fresh_tmp();
                let s = self.gen_inline(expr);
                self.local(&m, Some(s));
                let mut tests = Vec::new();
                let mut binds = Vec::new();
                self.pat_test(pat, LuaExpr::name(&m), &mut tests, &mut binds);
                self.lua.begin_if(and_all(tests));
                for (name, subj) in &binds {
                    self.local(self.local_name(name), Some(subj.clone()));
                }
                self.gen_block_to(body, &Dest::Discard);
                self.lua.begin_else();
                self.lua.break_statement();
                self.lua.end_block();
                if Self::block_has_continue(body) {
                    self.lua.label("continue");
                }
                self.lua.end_block();
            }
            Stmt::Break => self.lua.break_statement(),
            Stmt::Continue => self.lua.goto("continue"),
        }
    }

    fn gen_for(&mut self, var: &str, iter: &Expr, body: &Block) {
        let variable = self.local_name(var);
        if let Some(plan) = self.info.iter_plan(iter.id)
            && (!plan.adapters.is_empty()
                || matches!(
                    plan.source.kind,
                    IterSourceKind::VecIter | IterSourceKind::VecIntoIter
                ))
            && let Some(chain) = extract_iter_chain(iter, plan, false)
        {
            self.gen_iter_loop(&chain, plan, Some((&variable, body)), &Dest::Discard);
            return;
        }
        if let ExprKind::Range {
            start,
            end,
            inclusive,
        } = &iter.kind
        {
            let s = self.gen_inline(start);
            let e = self.gen_inline(end);
            let stop = if *inclusive {
                e
            } else if let ExprKind::Int(n) = &end.kind {
                // Compile-time constant: `0..5` → `0, 4`
                n.parse::<i64>()
                    .ok()
                    .map(|v| LuaExpr::integer((v - 1).to_string()))
                    .unwrap_or_else(|| e.clone().binary(LuaBinaryOp::Sub, LuaExpr::integer("1")))
            } else {
                e.binary(LuaBinaryOp::Sub, LuaExpr::integer("1"))
            };
            self.lua.begin_numeric_for(&variable, s, stop);
            self.gen_block_to(body, &Dest::Discard);
            if Self::block_has_continue(body) {
                self.lua.label("continue");
            }
            self.lua.end_block();
        } else {
            // General iterable: a Vec `{ [0..n-1], n = len }`.
            let it = self.gen_inline(iter);
            let holder = self.fresh_tmp();
            self.local(&holder, Some(it));
            let idx = self.fresh_tmp();
            self.lua.begin_numeric_for(
                &idx,
                LuaExpr::integer("0"),
                LuaExpr::name(&holder)
                    .field("n")
                    .binary(LuaBinaryOp::Sub, LuaExpr::integer("1")),
            );
            self.local(
                &variable,
                Some(LuaExpr::name(&holder).index(LuaExpr::name(&idx))),
            );
            self.gen_block_to(body, &Dest::Discard);
            if Self::block_has_continue(body) {
                self.lua.label("continue");
            }
            self.lua.end_block();
        }
    }

    fn gen_closure_local(&mut self, name: &str, params: &[ClosureParam], body: &ClosureBody) {
        let params = params
            .iter()
            .map(|param| self.local_name(&param.name))
            .collect::<Vec<_>>();
        self.lua.begin_function(FunctionTarget::local(name), params);
        match body {
            ClosureBody::Expr(expr) => self.gen_expr_to(expr, &Dest::Return),
            ClosureBody::Block(block) => self.gen_block_to(block, &Dest::Return),
        }
        self.lua.end_block();
    }

    fn gen_closure_value(&mut self, params: &[ClosureParam], body: &ClosureBody) -> LuaExpr {
        let local = self.fresh_tmp();
        self.gen_closure_local(&local, params, body);
        LuaExpr::name(local)
    }

    fn gen_inlined_closure(&mut self, closure: &Expr, inputs: &[LuaExpr]) -> LuaExpr {
        let ExprKind::Closure { params, body, .. } = &closure.kind else {
            return LuaExpr::Nil;
        };
        let result = self.fresh_tmp();
        let done =
            matches!(body, ClosureBody::Block(_)).then(|| format!("{}_done", self.fresh_tmp()));
        self.local(&result, None);
        self.lua.begin_do();
        for (param, input) in params.iter().zip(inputs) {
            self.local(self.local_name(&param.name), Some(input.clone()));
        }
        match body {
            ClosureBody::Expr(expr) => self.gen_expr_to(expr, &Dest::Var(LuaExpr::name(&result))),
            ClosureBody::Block(block) => {
                let done = done.as_ref().unwrap();
                self.closure_return_targets
                    .push((result.clone(), done.clone()));
                self.gen_block_to(block, &Dest::Var(LuaExpr::name(&result)));
                self.closure_return_targets.pop();
            }
        }
        self.lua.end_block();
        if let Some(done) = done {
            self.lua.label(done);
        }
        LuaExpr::name(result)
    }

    fn gen_iter_loop(
        &mut self,
        chain: &IterChain<'_>,
        plan: &IterPlan,
        for_body: Option<(&str, &Block)>,
        dest: &Dest,
    ) {
        let source = match plan.source.kind {
            IterSourceKind::ExclusiveRange | IterSourceKind::InclusiveRange => {
                let ExprKind::Range { start, end, .. } = &chain.source.kind else {
                    return;
                };
                let start_value = self.gen_inline(start);
                let start_local = self.fresh_tmp();
                self.local(&start_local, Some(start_value));
                let end_value = self.gen_inline(end);
                let end_local = self.fresh_tmp();
                self.local(&end_local, Some(end_value));
                IterLoopSource::Range {
                    start: start_local,
                    end: end_local,
                    inclusive: plan.source.kind == IterSourceKind::InclusiveRange,
                }
            }
            IterSourceKind::Vec | IterSourceKind::VecIter | IterSourceKind::VecIntoIter => {
                let value = self.gen_inline(chain.source);
                let holder = self.fresh_tmp();
                self.local(&holder, Some(value));
                IterLoopSource::Vec { holder }
            }
        };

        let mut states = Vec::with_capacity(chain.adapters.len());
        for adapter in &chain.adapters {
            let mut state = IterAdapterState::default();
            match adapter.kind {
                IterAdapterKind::Enumerate => {
                    let counter = self.fresh_tmp();
                    self.local(&counter, Some(LuaExpr::integer("0")));
                    state.counter = Some(counter);
                }
                IterAdapterKind::Skip | IterAdapterKind::Take => {
                    let limit_value = adapter
                        .args
                        .first()
                        .map(|arg| self.gen_inline(arg))
                        .unwrap_or_else(|| LuaExpr::integer("0"));
                    let limit = self.fresh_tmp();
                    self.local(&limit, Some(limit_value));
                    let counter = self.fresh_tmp();
                    self.local(&counter, Some(LuaExpr::integer("0")));
                    state.limit = Some(limit);
                    state.counter = Some(counter);
                }
                _ => {}
            }
            states.push(state);
        }

        let result = match plan.consumer {
            IterConsumerKind::For => None,
            IterConsumerKind::CollectVec => {
                self.uses_rt = true;
                let result = self.fresh_tmp();
                self.local(
                    &result,
                    Some(rt_call(
                        "vec",
                        vec![LuaExpr::named_table(vec![(
                            "n".into(),
                            LuaExpr::integer("0"),
                        )])],
                    )),
                );
                Some(result)
            }
            IterConsumerKind::Fold => {
                let init = chain
                    .consumer_args
                    .first()
                    .map(|arg| self.gen_inline(arg))
                    .unwrap_or(LuaExpr::Nil);
                let result = self.fresh_tmp();
                self.local(&result, Some(init));
                Some(result)
            }
            IterConsumerKind::Count => {
                let result = self.fresh_tmp();
                self.local(&result, Some(LuaExpr::integer("0")));
                Some(result)
            }
            IterConsumerKind::Any | IterConsumerKind::All => {
                let result = self.fresh_tmp();
                let initial = plan.consumer == IterConsumerKind::All;
                self.local(&result, Some(LuaExpr::Bool(initial)));
                Some(result)
            }
            IterConsumerKind::Find => {
                let result = self.fresh_tmp();
                self.local(&result, Some(LuaExpr::Nil));
                Some(result)
            }
        };

        let item = self.fresh_tmp();
        match &source {
            IterLoopSource::Range {
                start,
                end,
                inclusive,
            } => {
                let stop = if *inclusive {
                    LuaExpr::name(end)
                } else {
                    LuaExpr::name(end).binary(LuaBinaryOp::Sub, LuaExpr::integer("1"))
                };
                let index = self.fresh_tmp();
                self.lua
                    .begin_numeric_for(&index, LuaExpr::name(start), stop);
                self.local(&item, Some(LuaExpr::name(index)));
            }
            IterLoopSource::Vec { holder } => {
                let index = self.fresh_tmp();
                self.lua.begin_numeric_for(
                    &index,
                    LuaExpr::integer("0"),
                    LuaExpr::name(holder)
                        .field("n")
                        .binary(LuaBinaryOp::Sub, LuaExpr::integer("1")),
                );
                self.local(
                    &item,
                    Some(LuaExpr::name(holder).index(LuaExpr::name(index))),
                );
            }
        }
        let active = self.fresh_tmp();
        self.local(&active, Some(LuaExpr::Bool(true)));

        for (adapter, state) in chain.adapters.iter().zip(&states) {
            self.lua.begin_if(LuaExpr::name(&active));
            match adapter.kind {
                IterAdapterKind::Map => {
                    if let Some(closure) = adapter.args.first() {
                        let mapped = self.gen_inlined_closure(
                            closure,
                            std::slice::from_ref(&LuaExpr::name(&item)),
                        );
                        self.assign(LuaExpr::name(&item), mapped);
                    }
                }
                IterAdapterKind::Filter => {
                    if let Some(closure) = adapter.args.first() {
                        let keep = self.gen_inlined_closure(
                            closure,
                            std::slice::from_ref(&LuaExpr::name(&item)),
                        );
                        self.lua.compact_if(
                            LuaExpr::unary(LuaUnaryOp::Not, keep),
                            vec![InlineStatement::assign(
                                LuaExpr::name(&active),
                                LuaExpr::Bool(false),
                            )],
                        );
                    }
                }
                IterAdapterKind::FilterMap => {
                    if let Some(closure) = adapter.args.first() {
                        let mapped = self.gen_inlined_closure(
                            closure,
                            std::slice::from_ref(&LuaExpr::name(&item)),
                        );
                        self.lua
                            .begin_if(mapped.clone().binary(LuaBinaryOp::Eq, LuaExpr::Nil));
                        self.assign(LuaExpr::name(&active), LuaExpr::Bool(false));
                        self.lua.begin_else();
                        self.assign(LuaExpr::name(&item), mapped);
                        self.lua.end_block();
                    }
                }
                IterAdapterKind::Enumerate => {
                    let counter = state.counter.as_deref().unwrap_or("0");
                    self.assign(
                        LuaExpr::name(&item),
                        LuaExpr::Table(vec![
                            TableField::Indexed(LuaExpr::integer("0"), LuaExpr::name(counter)),
                            TableField::Indexed(LuaExpr::integer("1"), LuaExpr::name(&item)),
                            TableField::Named("n".into(), LuaExpr::integer("2")),
                        ]),
                    );
                    self.assign(
                        LuaExpr::name(counter),
                        LuaExpr::name(counter).binary(LuaBinaryOp::Add, LuaExpr::integer("1")),
                    );
                }
                IterAdapterKind::Skip => {
                    let counter = state.counter.as_deref().unwrap_or("0");
                    let limit = state.limit.as_deref().unwrap_or("0");
                    self.lua.begin_if(
                        LuaExpr::name(counter).binary(LuaBinaryOp::Lt, LuaExpr::name(limit)),
                    );
                    self.assign(
                        LuaExpr::name(counter),
                        LuaExpr::name(counter).binary(LuaBinaryOp::Add, LuaExpr::integer("1")),
                    );
                    self.assign(LuaExpr::name(&active), LuaExpr::Bool(false));
                    self.lua.end_block();
                }
                IterAdapterKind::Take => {
                    let counter = state.counter.as_deref().unwrap_or("0");
                    let limit = state.limit.as_deref().unwrap_or("0");
                    self.lua.compact_if(
                        LuaExpr::name(counter).binary(LuaBinaryOp::Ge, LuaExpr::name(limit)),
                        vec![InlineStatement::Break],
                    );
                    self.assign(
                        LuaExpr::name(counter),
                        LuaExpr::name(counter).binary(LuaBinaryOp::Add, LuaExpr::integer("1")),
                    );
                }
            }
            self.lua.end_block();
        }

        self.lua.begin_if(LuaExpr::name(&active));
        match plan.consumer {
            IterConsumerKind::For => {
                if let Some((var, body)) = for_body {
                    self.local(var, Some(LuaExpr::name(&item)));
                    self.gen_block_to(body, &Dest::Discard);
                }
            }
            IterConsumerKind::CollectVec => {
                let result = result.as_deref().unwrap();
                let length = LuaExpr::name(result).field("n");
                self.assign(
                    LuaExpr::name(result).index(length.clone()),
                    LuaExpr::name(&item),
                );
                self.assign(
                    length.clone(),
                    length.binary(LuaBinaryOp::Add, LuaExpr::integer("1")),
                );
            }
            IterConsumerKind::Fold => {
                if let (Some(result), Some(closure)) =
                    (result.as_deref(), chain.consumer_args.get(1))
                {
                    let inputs = [LuaExpr::name(result), LuaExpr::name(&item)];
                    let next = self.gen_inlined_closure(closure, &inputs);
                    self.assign(LuaExpr::name(result), next);
                }
            }
            IterConsumerKind::Count => {
                let result = result.as_deref().unwrap();
                self.assign(
                    LuaExpr::name(result),
                    LuaExpr::name(result).binary(LuaBinaryOp::Add, LuaExpr::integer("1")),
                );
            }
            IterConsumerKind::Any | IterConsumerKind::All | IterConsumerKind::Find => {
                if let (Some(result), Some(predicate)) =
                    (result.as_deref(), chain.consumer_args.first())
                {
                    let matches = self.gen_inlined_closure(
                        predicate,
                        std::slice::from_ref(&LuaExpr::name(&item)),
                    );
                    match plan.consumer {
                        IterConsumerKind::Any => {
                            self.lua.compact_if(
                                matches,
                                vec![
                                    InlineStatement::assign(
                                        LuaExpr::name(result),
                                        LuaExpr::Bool(true),
                                    ),
                                    InlineStatement::Break,
                                ],
                            );
                        }
                        IterConsumerKind::All => {
                            self.lua.compact_if(
                                LuaExpr::unary(LuaUnaryOp::Not, matches),
                                vec![
                                    InlineStatement::assign(
                                        LuaExpr::name(result),
                                        LuaExpr::Bool(false),
                                    ),
                                    InlineStatement::Break,
                                ],
                            );
                        }
                        IterConsumerKind::Find => {
                            self.lua.compact_if(
                                matches,
                                vec![
                                    InlineStatement::assign(
                                        LuaExpr::name(result),
                                        LuaExpr::name(&item),
                                    ),
                                    InlineStatement::Break,
                                ],
                            );
                        }
                        _ => {}
                    }
                }
            }
        }
        self.lua.end_block();

        if plan.consumer == IterConsumerKind::For
            && let Some((_, body)) = for_body
            && Self::block_has_continue(body)
        {
            self.lua.label("continue");
        }
        for (adapter, state) in chain.adapters.iter().zip(&states) {
            if adapter.kind == IterAdapterKind::Take {
                let counter = state.counter.as_deref().unwrap_or("0");
                let limit = state.limit.as_deref().unwrap_or("0");
                self.lua.compact_if(
                    LuaExpr::name(counter).binary(LuaBinaryOp::Ge, LuaExpr::name(limit)),
                    vec![InlineStatement::Break],
                );
            }
        }
        self.lua.end_block();

        if let Some(result) = result {
            match dest {
                Dest::Var(target) => self.assign(target.clone(), LuaExpr::name(result)),
                Dest::Return => self.return_value(LuaExpr::name(result)),
                Dest::Discard => {}
            }
        }
    }

    // --- expression to destination ----------------------------------------

    fn gen_block_to(&mut self, block: &Block, dest: &Dest) {
        for s in &block.stmts {
            self.gen_stmt(s);
        }
        match &block.tail {
            Some(e) => self.gen_expr_to(e, dest),
            None => {
                if let Dest::Var(d) = dest {
                    self.assign(d.clone(), LuaExpr::Nil);
                }
            }
        }
    }

    fn gen_expr_to(&mut self, expression: &Expr, dest: &Dest) {
        self.lua.push_anchor(expression.span);
        self.gen_expr_to_inner(expression, dest);
        self.lua.pop_anchor();
    }

    fn gen_expr_to_inner(&mut self, e: &Expr, dest: &Dest) {
        if let Some(plan) = self.info.iter_plan(e.id)
            && let Some(chain) = extract_iter_chain(e, plan, true)
        {
            self.gen_iter_loop(&chain, plan, None, dest);
            return;
        }
        match &e.kind {
            ExprKind::If {
                cond,
                then_block,
                else_block,
            } => {
                let c = self.gen_inline(cond);
                self.lua.begin_if(c);
                self.gen_block_to(then_block, dest);
                match else_block.as_deref() {
                    Some(ElseBranch::Block(b)) => {
                        self.lua.begin_else();
                        self.gen_block_to(b, dest);
                    }
                    Some(ElseBranch::If(inner)) => {
                        self.lua.begin_else();
                        self.gen_expr_to(inner, dest);
                    }
                    None => {
                        if let Dest::Var(d) = dest {
                            self.lua.begin_else();
                            self.assign(d.clone(), LuaExpr::Nil);
                        }
                    }
                }
                self.lua.end_block();
            }
            ExprKind::IfLet {
                pat,
                expr,
                then_block,
                else_block,
            } => {
                let m = self.fresh_tmp();
                let s = self.gen_inline(expr);
                self.local(&m, Some(s));
                let mut tests = Vec::new();
                let mut binds = Vec::new();
                self.pat_test(pat, LuaExpr::name(&m), &mut tests, &mut binds);
                self.lua.begin_if(and_all(tests));
                for (name, subj) in &binds {
                    self.local(self.local_name(name), Some(subj.clone()));
                }
                self.gen_block_to(then_block, dest);
                match else_block.as_deref() {
                    Some(ElseBranch::Block(b)) => {
                        self.lua.begin_else();
                        self.gen_block_to(b, dest);
                    }
                    Some(ElseBranch::If(inner)) => {
                        self.lua.begin_else();
                        self.gen_expr_to(inner, dest);
                    }
                    None => {
                        if let Dest::Var(d) = dest {
                            self.lua.begin_else();
                            self.assign(d.clone(), LuaExpr::Nil);
                        }
                    }
                }
                self.lua.end_block();
            }
            ExprKind::Block(b) => self.gen_block_to(b, dest),
            ExprKind::Match { scrut, arms } => self.gen_match(scrut, arms, dest),
            ExprKind::Assign { target, value } => {
                let t = self.gen_inline(target);
                self.gen_expr_to(value, &Dest::Var(t));
                match dest {
                    Dest::Var(d) => self.assign(d.clone(), LuaExpr::Nil),
                    Dest::Return => self.return_value(LuaExpr::Nil),
                    Dest::Discard => {}
                }
            }
            _ => {
                let v = self.gen_inline(e);
                match dest {
                    Dest::Discard => {
                        if matches!(
                            e.kind,
                            ExprKind::Call { .. }
                                | ExprKind::MethodCall { .. }
                                | ExprKind::MacroCall { .. }
                        ) {
                            self.expression_statement(v);
                        }
                    }
                    Dest::Var(d) => self.assign(d.clone(), v),
                    Dest::Return => self.return_value(v),
                }
            }
        }
    }

    // --- match -------------------------------------------------------------

    fn gen_match(&mut self, scrut: &Expr, arms: &[MatchArm], dest: &Dest) {
        let m = self.fresh_tmp();
        let s = self.gen_inline(scrut);
        self.local(&m, Some(s));
        let matched = self.fresh_tmp();
        self.local(&matched, Some(LuaExpr::Bool(false)));

        for arm in arms {
            let (tests, binds) = self.arm_tests(arm, LuaExpr::name(&m));
            let unmatched = LuaExpr::unary(LuaUnaryOp::Not, LuaExpr::name(&matched));
            let condition = if tests.is_empty() {
                unmatched
            } else {
                unmatched.binary(LuaBinaryOp::And, and_all(tests).parenthesized())
            };
            self.lua.begin_if(condition);

            for (name, subj) in &binds {
                self.local(self.local_name(name), Some(subj.clone()));
            }
            let guard = arm.guard.as_ref().map(|g| self.gen_inline(g));
            if let Some(g) = &guard {
                self.lua.begin_if(g.clone());
            }

            self.assign(LuaExpr::name(&matched), LuaExpr::Bool(true));
            self.gen_expr_to(&arm.body, dest);

            if guard.is_some() {
                self.lua.end_block();
            }
            self.lua.end_block();
        }

        self.lua.compact_if(
            LuaExpr::unary(LuaUnaryOp::Not, LuaExpr::name(matched)),
            vec![InlineStatement::expression(
                LuaExpr::name("error").call(vec![LuaExpr::string("non-exhaustive match")]),
            )],
        );
    }

    /// Structural tests + bindings for a match arm against subject variable `m`.
    fn arm_tests(
        &mut self,
        arm: &MatchArm,
        subject: LuaExpr,
    ) -> (Vec<LuaExpr>, Vec<(String, LuaExpr)>) {
        if arm.pats.len() == 1 {
            let mut tests = Vec::new();
            let mut binds = Vec::new();
            self.pat_test(&arm.pats[0], subject, &mut tests, &mut binds);
            (tests, binds)
        } else {
            // or-patterns: combine alternatives; bindings are not supported here.
            let mut alts = Vec::new();
            for p in &arm.pats {
                let mut tests = Vec::new();
                let mut binds = Vec::new();
                self.pat_test(p, subject.clone(), &mut tests, &mut binds);
                alts.push(and_all(tests).parenthesized());
            }
            (vec![or_all(alts)], Vec::new())
        }
    }

    fn pat_test(
        &mut self,
        pat: &Pattern,
        subject: LuaExpr,
        tests: &mut Vec<LuaExpr>,
        binds: &mut Vec<(String, LuaExpr)>,
    ) {
        match pat {
            Pattern::Wildcard => {}
            Pattern::Binding(name, _) => binds.push((name.clone(), subject)),
            Pattern::Literal(lit) => {
                let v = self.gen_inline(lit);
                tests.push(subject.binary(LuaBinaryOp::Eq, v));
            }
            Pattern::Range { lo, hi, inclusive } => {
                let l = self.gen_inline(lo);
                let h = self.gen_inline(hi);
                let upper = if *inclusive {
                    LuaBinaryOp::Le
                } else {
                    LuaBinaryOp::Lt
                };
                tests.push(
                    subject
                        .clone()
                        .binary(LuaBinaryOp::Ge, l)
                        .binary(LuaBinaryOp::And, subject.binary(upper, h))
                        .parenthesized(),
                );
            }
            Pattern::Path { id, .. } => {
                let target = self.pattern_target(*id);
                match target {
                    crate::hir::ResolvedTarget::Builtin(rua_core::BuiltinId::VariantOptionNone) => {
                        tests.push(subject.binary(LuaBinaryOp::Eq, LuaExpr::Nil));
                    }
                    crate::hir::ResolvedTarget::Builtin(rua_core::BuiltinId::VariantOptionSome) => {
                        tests.push(subject.binary(LuaBinaryOp::Ne, LuaExpr::Nil))
                    }
                    crate::hir::ResolvedTarget::Builtin(rua_core::BuiltinId::VariantResultOk) => {
                        tests.push(
                            subject
                                .field("tag")
                                .binary(LuaBinaryOp::Eq, LuaExpr::string("ok")),
                        )
                    }
                    crate::hir::ResolvedTarget::Builtin(rua_core::BuiltinId::VariantResultErr) => {
                        tests.push(
                            subject
                                .field("tag")
                                .binary(LuaBinaryOp::Eq, LuaExpr::string("err")),
                        )
                    }
                    _ => {
                        let (_, variant, _) = self
                            .resolve_variant(Some(target))
                            .expect("checked path pattern resolves to an enum variant");
                        tests.push(subject.field("tag").binary(
                            LuaBinaryOp::Eq,
                            LuaExpr::string(&self.hir.definition(variant).name),
                        ));
                    }
                }
            }
            Pattern::TupleVariant { id, elems, .. } => {
                let target = self.pattern_target(*id);
                match target {
                    crate::hir::ResolvedTarget::Builtin(rua_core::BuiltinId::VariantOptionSome) => {
                        // Some(x) is the bare value; None is nil.
                        tests.push(subject.clone().binary(LuaBinaryOp::Ne, LuaExpr::Nil));
                        if let Some(inner) = elems.first() {
                            self.pat_test(inner, subject, tests, binds);
                        }
                    }
                    crate::hir::ResolvedTarget::Builtin(rua_core::BuiltinId::VariantResultOk) => {
                        tests.push(
                            subject
                                .clone()
                                .field("tag")
                                .binary(LuaBinaryOp::Eq, LuaExpr::string("ok")),
                        );
                        if let Some(inner) = elems.first() {
                            self.pat_test(inner, subject.field("value"), tests, binds);
                        }
                    }
                    crate::hir::ResolvedTarget::Builtin(rua_core::BuiltinId::VariantResultErr) => {
                        tests.push(
                            subject
                                .clone()
                                .field("tag")
                                .binary(LuaBinaryOp::Eq, LuaExpr::string("err")),
                        );
                        if let Some(inner) = elems.first() {
                            self.pat_test(inner, subject.field("value"), tests, binds);
                        }
                    }
                    _ => {
                        let (_, variant, crate::hir::VariantShape::Tuple) = self
                            .resolve_variant(Some(target))
                            .expect("checked tuple pattern resolves to a tuple enum variant")
                        else {
                            unreachable!("checked tuple pattern has tuple variant shape")
                        };
                        tests.push(subject.clone().field("tag").binary(
                            LuaBinaryOp::Eq,
                            LuaExpr::string(&self.hir.definition(variant).name),
                        ));
                        for (i, elem) in elems.iter().enumerate() {
                            let sub = subject.clone().index(LuaExpr::integer((i + 1).to_string()));
                            self.pat_test(elem, sub, tests, binds);
                        }
                    }
                }
            }
            Pattern::StructVariant {
                id,
                path: _,
                fields,
                ..
            } => {
                // If it resolves to an enum variant, test the tag; a plain struct
                // pattern needs no tag test.
                if let Some((_, variant, _)) =
                    self.resolve_variant(Some(self.program.pattern_target(*id)))
                {
                    tests.push(subject.clone().field("tag").binary(
                        LuaBinaryOp::Eq,
                        LuaExpr::string(&self.hir.definition(variant).name),
                    ));
                }
                for (fname, fpat) in fields {
                    let sub = subject.clone().field(self.layout.member_name(fname));
                    self.pat_test(fpat, sub, tests, binds);
                }
            }
        }
    }

    // --- inline (pure Lua expression, may hoist) --------------------------

    fn gen_inline(&mut self, expression: &Expr) -> LuaExpr {
        self.lua.push_anchor(expression.span);
        let value = self.gen_inline_inner(expression);
        self.lua.pop_anchor();
        value
    }

    fn gen_inline_inner(&mut self, e: &Expr) -> LuaExpr {
        if let Some(plan) = self.info.iter_plan(e.id)
            && let Some(chain) = extract_iter_chain(e, plan, true)
        {
            let tmp = self.fresh_tmp();
            self.local(&tmp, None);
            self.gen_iter_loop(&chain, plan, None, &Dest::Var(LuaExpr::name(&tmp)));
            return LuaExpr::name(tmp);
        }
        match &e.kind {
            ExprKind::Int(s) => LuaExpr::integer(lua_int_literal(s)),
            ExprKind::Float(s) => LuaExpr::number(s.replace('_', "")),
            ExprKind::Str(s) => LuaExpr::string_literal(s),
            ExprKind::Bool(value) => LuaExpr::Bool(*value),
            ExprKind::Closure { params, body, .. } => self.gen_closure_value(params, body),
            ExprKind::Path(_) => self.gen_path(e),
            ExprKind::Unary { op, expr } => {
                let inner = self.gen_inline(expr);
                match op {
                    UnOp::Neg => LuaExpr::unary(LuaUnaryOp::Neg, inner),
                    UnOp::Not => LuaExpr::unary(LuaUnaryOp::Not, inner),
                }
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let l = self.gen_inline(lhs);
                let r = self.gen_inline(rhs);
                // `i64 / i64` and `i64 % i64` lower to `rt.idiv`/`rt.irem`, which
                // truncate toward zero to match Rust (Lua `//`/`%` floor, differing
                // when exactly one operand is negative: Rust `-7/2 == -3`,
                // `-7%2 == -1` vs Lua `-7//2 == -4`, `-7%2 == 1`).
                if *op == BinOp::Div && self.info.is_int_div(e.id) {
                    self.uses_rt = true;
                    return rt_call("idiv", vec![l, r]);
                }
                if *op == BinOp::Rem && self.info.is_int_rem(e.id) {
                    self.uses_rt = true;
                    return rt_call("irem", vec![l, r]);
                }
                // `String + String` is Lua concatenation, not arithmetic.
                if *op == BinOp::Add && self.info.is_str_concat(e.id) {
                    return l.binary(LuaBinaryOp::Concat, r).parenthesized();
                }
                l.binary(binop_lua(*op), r)
            }
            ExprKind::Call { callee, args } => self.gen_call(callee, args),
            ExprKind::MethodCall {
                recv, method, args, ..
            } => {
                let r = self.gen_inline(recv);
                let a: Vec<LuaExpr> = args.iter().map(|x| self.gen_inline(x)).collect();
                // Recognized `String` methods route through `rt.str` (bracket
                // form avoids clashing with Lua keywords like `repeat`); the
                // receiver is passed as the first argument.
                if self.info.is_str_method(e.id) {
                    // Optimise: .to_string() / .to_owned() / .clone() on a
                    // string literal is a no-op — just return the literal.
                    let is_string_lit = matches!(&recv.kind, ExprKind::Str(..));
                    if is_string_lit
                        && matches!(method.as_str(), "to_string" | "to_owned" | "clone")
                    {
                        return r;
                    }
                    self.uses_rt = true;
                    let mut all = vec![r];
                    all.extend(a);
                    return LuaExpr::name("rt")
                        .field("str")
                        .index(LuaExpr::string(method))
                        .call(all);
                }
                // Option::map(f) — Some(v) compiles to v, None to nil.
                // Inline the closure application directly on the raw value.
                if self.info.is_option_map(e.id) && args.len() == 1 {
                    let val = self.fresh_tmp();
                    self.local(&val, Some(r));
                    self.lua
                        .begin_if(LuaExpr::name(&val).binary(LuaBinaryOp::Ne, LuaExpr::Nil));
                    if matches!(&args[0].kind, ExprKind::Closure { .. }) {
                        let applied = self.gen_inlined_closure(
                            &args[0],
                            std::slice::from_ref(&LuaExpr::name(&val)),
                        );
                        self.assign(LuaExpr::name(&val), applied);
                    }
                    self.lua.end_block();
                    return LuaExpr::name(val);
                }
                r.method_call(self.layout.member_name(method), a)
            }
            ExprKind::Field { base, name, .. } => {
                self.gen_inline(base).field(self.layout.member_name(name))
            }
            ExprKind::Index { base, index } => {
                let b = self.gen_inline(base);
                let i = self.gen_inline(index);
                b.index(i)
            }
            ExprKind::MacroCall { args, .. } => self.gen_macro(e, args),
            ExprKind::Range { start, end, .. } => {
                // Ranges are only meaningful as a `for` iterator; elsewhere they
                // have no first-class value.
                let _ = (start, end);
                LuaExpr::Nil
            }
            ExprKind::StructLit { fields, .. } => self.gen_struct_lit(e, fields),
            ExprKind::Try { expr } => {
                let inner = self.gen_inline(expr);
                let value = self.fresh_tmp();
                self.local(&value, Some(inner));
                if self.info.is_result_try(e.id) {
                    self.lua.compact_if(
                        LuaExpr::name(&value)
                            .field("tag")
                            .binary(LuaBinaryOp::Eq, LuaExpr::string("err")),
                        vec![InlineStatement::return_value(LuaExpr::name(&value))],
                    );
                    LuaExpr::name(value).field("value")
                } else {
                    self.lua.compact_if(
                        LuaExpr::name(&value).binary(LuaBinaryOp::Eq, LuaExpr::Nil),
                        vec![InlineStatement::return_nil()],
                    );
                    LuaExpr::name(value)
                }
            }
            // Control-flow in operand position: hoist into a temp.
            ExprKind::If { .. }
            | ExprKind::IfLet { .. }
            | ExprKind::Block(_)
            | ExprKind::Match { .. }
            | ExprKind::Assign { .. } => {
                let tmp = self.fresh_tmp();
                self.local(&tmp, None);
                self.gen_expr_to(e, &Dest::Var(LuaExpr::name(&tmp)));
                LuaExpr::name(tmp)
            }
        }
    }

    fn gen_path(&mut self, expression: &Expr) -> LuaExpr {
        let target = self.program.expression_target(expression.id);
        if let crate::hir::ResolvedTarget::Builtin(builtin) = target
            && matches!(
                self.builtin_rules.get(builtin),
                Some(crate::builtins::CodegenRule::Nil)
            )
        {
            return LuaExpr::Nil;
        }
        if let Some((owner, variant, shape)) = self.resolve_variant(Some(target))
            && let crate::hir::VariantShape::Unit = shape
        {
            let meta = self
                .target_place(crate::hir::ResolvedTarget::Item(owner))
                .expect("enum owner has a backend place");
            return setmetatable(
                LuaExpr::named_table(vec![(
                    "tag".into(),
                    LuaExpr::string(&self.hir.definition(variant).name),
                )]),
                meta.expression(),
            );
        }
        if let Some(place) = self.target_place(target) {
            return place.expression();
        }
        panic!("typed expression {:?} has no backend place", expression.id)
    }

    fn target_place(
        &self,
        target: crate::hir::ResolvedTarget,
    ) -> Option<crate::backend_layout::Place> {
        self.layout.target(target).cloned()
    }

    fn resolve_variant(
        &self,
        target: Option<crate::hir::ResolvedTarget>,
    ) -> Option<(
        crate::hir::DefId,
        crate::hir::DefId,
        crate::hir::VariantShape,
    )> {
        let crate::hir::ResolvedTarget::Item(variant) = target? else {
            return None;
        };
        let crate::hir::DefKind::EnumVariant { owner, shape } = self.hir.definition(variant).kind
        else {
            return None;
        };
        Some((owner, variant, shape))
    }

    fn pattern_target(&self, id: PatternId) -> crate::hir::ResolvedTarget {
        self.program.pattern_target(id)
    }

    fn gen_call(&mut self, callee: &Expr, args: &[Expr]) -> LuaExpr {
        if matches!(callee.kind, ExprKind::Path(_)) {
            // Check codegen rules for builtin constructors.
            let rule = match self.program.expression_target(callee.id) {
                crate::hir::ResolvedTarget::Builtin(builtin) => self.builtin_rules.get(builtin),
                _ => None,
            };
            if let Some(rule) = rule {
                use crate::builtins::CodegenRule::*;
                match rule {
                    InlineArg if !args.is_empty() => return self.gen_inline(&args[0]),
                    TaggedResult { ok } if !args.is_empty() => {
                        let v = self.gen_inline(&args[0]);
                        self.uses_rt = true;
                        let constructor = if *ok { "result_ok" } else { "result_err" };
                        return rt_call(constructor, vec![v]);
                    }
                    EmptyVec => {
                        self.uses_rt = true;
                        return rt_call(
                            "vec",
                            vec![LuaExpr::named_table(vec![(
                                "n".into(),
                                LuaExpr::integer("0"),
                            )])],
                        );
                    }
                    EmptyMap => {
                        self.uses_rt = true;
                        return rt_call("map", Vec::new());
                    }
                    _ => {}
                }
            }
            // Enum tuple-variant construction.
            let target = Some(self.program.expression_target(callee.id));
            if let Some((owner, variant, crate::hir::VariantShape::Tuple)) =
                self.resolve_variant(target)
            {
                let a: Vec<LuaExpr> = args.iter().map(|x| self.gen_inline(x)).collect();
                let meta = self
                    .target_place(crate::hir::ResolvedTarget::Item(owner))
                    .expect("enum owner has a backend place");
                let mut fields = vec![TableField::Named(
                    "tag".into(),
                    LuaExpr::string(&self.hir.definition(variant).name),
                )];
                fields.extend(a.into_iter().map(TableField::Value));
                return setmetatable(LuaExpr::Table(fields), meta.expression());
            }
            // Associated function `Type::func(..)` or plain call.
            let a = args.iter().map(|x| self.gen_inline(x)).collect();
            return self.gen_path(callee).call(a);
        }
        let c = self.gen_inline(callee);
        let a = args.iter().map(|x| self.gen_inline(x)).collect();
        c.call(a)
    }

    fn gen_macro(&mut self, expression: &Expr, args: &[Expr]) -> LuaExpr {
        let a: Vec<LuaExpr> = args.iter().map(|x| self.gen_inline(x)).collect();
        let crate::hir::ResolvedTarget::Builtin(builtin) =
            self.program.expression_target(expression.id)
        else {
            panic!(
                "checked macro call {:?} has no builtin identity",
                expression.id
            );
        };
        let spec = builtin_macro_by_id(builtin)
            .unwrap_or_else(|| panic!("resolved builtin {builtin:?} is not a macro"));
        let lowering = spec.lowering;
        match lowering {
            BuiltinMacroLowering::Vec => {
                self.uses_rt = true;
                // 0-based storage + length field, matching Rust indexing.
                let mut fields: Vec<TableField> = a
                    .into_iter()
                    .enumerate()
                    .map(|(index, value)| {
                        TableField::Indexed(LuaExpr::integer(index.to_string()), value)
                    })
                    .collect();
                fields.push(TableField::Named(
                    "n".into(),
                    LuaExpr::integer(fields.len().to_string()),
                ));
                rt_call("vec", vec![LuaExpr::Table(fields)])
            }
            BuiltinMacroLowering::Format => {
                self.uses_rt = true;
                rt_call("format", a)
            }
            BuiltinMacroLowering::Println => {
                self.uses_rt = true;
                rt_call("println", a)
            }
            BuiltinMacroLowering::Print => {
                self.uses_rt = true;
                rt_call("print", a)
            }
            BuiltinMacroLowering::Panic => {
                self.uses_rt = true;
                rt_call("panic", vec![rt_call("format", a)])
            }
            BuiltinMacroLowering::Passthrough => LuaExpr::name(spec.name).call(a),
        }
    }

    fn gen_struct_lit(&mut self, expression: &Expr, fields: &[(String, Expr)]) -> LuaExpr {
        let field_values: Vec<(String, LuaExpr)> = fields
            .iter()
            .map(|(name, expression)| (self.layout.member_name(name), self.gen_inline(expression)))
            .collect();

        // Struct variant of an enum?
        let target = Some(self.program.expression_target(expression.id));
        if let Some((owner, variant, crate::hir::VariantShape::Struct)) =
            self.resolve_variant(target)
        {
            let meta = self
                .target_place(crate::hir::ResolvedTarget::Item(owner))
                .expect("enum owner has a backend place");
            let mut values = vec![(
                "tag".into(),
                LuaExpr::string(&self.hir.definition(variant).name),
            )];
            values.extend(field_values);
            return setmetatable(LuaExpr::named_table(values), meta.expression());
        }

        let is_struct = matches!(
            target,
            Some(crate::hir::ResolvedTarget::Item(definition))
                if self.hir.definition(definition).kind == crate::hir::DefKind::Struct
        );
        if is_struct {
            let meta = self
                .target_place(self.program.expression_target(expression.id))
                .expect("checked struct literal target has a backend place");
            setmetatable(LuaExpr::named_table(field_values), meta.expression())
        } else {
            LuaExpr::named_table(field_values)
        }
    }
}

fn extract_iter_chain<'a>(
    expr: &'a Expr,
    plan: &IterPlan,
    has_consumer: bool,
) -> Option<IterChain<'a>> {
    let (mut cursor, consumer_args): (&Expr, &[Expr]) = if has_consumer {
        let ExprKind::MethodCall { recv, args, .. } = &expr.kind else {
            return None;
        };
        (recv, args)
    } else {
        (expr, &[])
    };

    let mut adapters = Vec::with_capacity(plan.adapters.len());
    for adapter in plan.adapters.iter().rev() {
        let ExprKind::MethodCall { recv, args, .. } = &cursor.kind else {
            return None;
        };
        adapters.push(IterCall {
            kind: adapter.kind,
            args,
        });
        cursor = recv;
    }
    adapters.reverse();

    if matches!(
        plan.source.kind,
        IterSourceKind::VecIter | IterSourceKind::VecIntoIter
    ) {
        let ExprKind::MethodCall { recv, .. } = &cursor.kind else {
            return None;
        };
        cursor = recv;
    }

    Some(IterChain {
        source: cursor,
        adapters,
        consumer_args,
    })
}

/// Collect trait declarations across all scopes, keyed by resolved identity.
fn collect_traits<'p>(
    items: &'p [Item],
    module: crate::hir::ModuleId,
    program: &crate::typed_ir::TypedProgram,
    out: &mut HashMap<crate::hir::DefId, &'p TraitDecl>,
) {
    for (item_index, item) in items.iter().enumerate() {
        match item {
            Item::Trait(t) => {
                out.insert(program.item_definition(module, item_index), t);
            }
            Item::Mod(m) => {
                let child = program.child_module(module, item_index);
                collect_traits(&m.items, child, program, out);
            }
            _ => {}
        }
    }
}

/// If `impl <trait> for T` defines the operator method `method`, return the Lua
/// metamethod name to alias it to (enabling `a + b`, `a == b`, etc.).
fn op_alias(target: crate::hir::TraitTarget, method: &str) -> Option<&'static str> {
    use rua_core::BuiltinTraitId;
    let crate::hir::TraitTarget::Builtin(trait_id) = target else {
        return None;
    };
    Some(match (trait_id, method) {
        (BuiltinTraitId::Add, "add") => "__add",
        (BuiltinTraitId::Sub, "sub") => "__sub",
        (BuiltinTraitId::Mul, "mul") => "__mul",
        (BuiltinTraitId::Div, "div") => "__div",
        (BuiltinTraitId::Rem, "rem") => "__mod",
        (BuiltinTraitId::Neg, "neg") => "__unm",
        (BuiltinTraitId::PartialEq | BuiltinTraitId::Eq, "eq") => "__eq",
        _ => return None,
    })
}

fn needs_hoist(e: &Expr) -> bool {
    matches!(
        e.kind,
        ExprKind::If { .. } | ExprKind::IfLet { .. } | ExprKind::Block(_) | ExprKind::Match { .. }
    )
}

fn binop_lua(op: BinOp) -> LuaBinaryOp {
    match op {
        BinOp::Add => LuaBinaryOp::Add,
        BinOp::Sub => LuaBinaryOp::Sub,
        BinOp::Mul => LuaBinaryOp::Mul,
        BinOp::Div => LuaBinaryOp::Div,
        BinOp::Rem => LuaBinaryOp::Rem,
        BinOp::Eq => LuaBinaryOp::Eq,
        BinOp::Ne => LuaBinaryOp::Ne,
        BinOp::Lt => LuaBinaryOp::Lt,
        BinOp::Le => LuaBinaryOp::Le,
        BinOp::Gt => LuaBinaryOp::Gt,
        BinOp::Ge => LuaBinaryOp::Ge,
        BinOp::And => LuaBinaryOp::And,
        BinOp::Or => LuaBinaryOp::Or,
    }
}

fn rt_call(name: &str, args: Vec<LuaExpr>) -> LuaExpr {
    LuaExpr::name("rt").field(name).call(args)
}

fn setmetatable(table: LuaExpr, metatable: LuaExpr) -> LuaExpr {
    LuaExpr::name("setmetatable").call(vec![table, metatable])
}

fn and_all(expressions: Vec<LuaExpr>) -> LuaExpr {
    expressions
        .into_iter()
        .reduce(|left, right| left.binary(LuaBinaryOp::And, right))
        .unwrap_or(LuaExpr::Bool(true))
}

fn or_all(expressions: Vec<LuaExpr>) -> LuaExpr {
    expressions
        .into_iter()
        .reduce(|left, right| left.binary(LuaBinaryOp::Or, right))
        .unwrap_or(LuaExpr::Bool(false))
}

fn lua_int_literal(s: &str) -> String {
    let clean = s.replace('_', "");
    if let Some(bits) = clean
        .strip_prefix("0b")
        .or_else(|| clean.strip_prefix("0B"))
        && let Ok(v) = i64::from_str_radix(bits, 2)
    {
        return v.to_string();
    }
    clean
}
