//! Lua traceback parsing and generated-to-Rua stack conversion.
//!
//! Lua reports source locations as chunk paths plus 1-based line numbers. The
//! compiler source map uses generated byte offsets, so this module keeps the
//! conversion at the host boundary: parse the Lua text, resolve each generated
//! line through the source map, and preserve frames that belong to the runtime
//! or an unmapped generated region.

use crate::{codegen::LuaSourceMapping, token::SourceRange};

/// One frame parsed from Lua's human-readable traceback.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LuaStackFrame {
    /// Chunk path reported by Lua, for example `main.lua` or `[C]`.
    pub source: String,
    /// 1-based Lua line, when the frame has one.
    pub line: Option<usize>,
    /// Text following `in`, kept without guessing whether it is a local or
    /// global function.
    pub function: Option<String>,
    /// Original frame line, useful for diagnostics and unknown Lua formats.
    pub raw: String,
}

/// A parsed Lua traceback before source-map conversion.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LuaTraceback {
    /// The error message, without the leading `lua:` prefix.
    pub message: String,
    /// Frames in the order reported by Lua. The first frame is the error
    /// location when the first traceback line contains a source location.
    pub frames: Vec<LuaStackFrame>,
}

/// One converted Rua frame. Unmapped Lua/runtime frames remain visible with
/// `rua_range == None`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RuaStackFrame {
    pub lua: LuaStackFrame,
    /// Source file path resolved from the source-file registry, if available.
    pub rua_file: Option<String>,
    /// Stable compiler source file identity, if the frame maps to Rua code.
    pub rua_file_id: Option<u32>,
    /// Source range anchored by code generation, if the frame maps to Rua.
    pub rua_range: Option<SourceRange>,
}

/// A Lua traceback with each frame resolved through a generated source map.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RuaTraceback {
    pub message: String,
    pub frames: Vec<RuaStackFrame>,
}

/// Parse Lua's default traceback format.
///
/// This accepts both the initial error location (`lua: file.lua:12: message`)
/// and stack frames (`file.lua:12: in function 'name'`). Unknown lines are
/// ignored except for `[C]: in ?`-style frames, which are retained as unmapped
/// frames.
pub fn parse_lua_traceback(traceback: &str) -> LuaTraceback {
    let mut lines = traceback.lines();
    let first = lines.next().unwrap_or_default().trim();
    let message_line = first.strip_prefix("lua:").unwrap_or(first).trim();
    let (message, error_frame) = if let Some((source, line, suffix)) = parse_location(message_line)
    {
        (
            suffix
                .strip_prefix(':')
                .map(str::trim)
                .unwrap_or_default()
                .to_string(),
            Some(LuaStackFrame {
                source,
                line: Some(line),
                function: None,
                raw: first.to_string(),
            }),
        )
    } else {
        (message_line.to_string(), None)
    };

    let mut frames = Vec::new();
    if let Some(frame) = error_frame {
        frames.push(frame);
    }
    for line in lines {
        let raw = line.trim();
        if raw.is_empty() || raw == "stack traceback:" {
            continue;
        }
        let Some((source, line_number, suffix)) = parse_location(raw) else {
            if let Some(source) = raw.strip_suffix(": in ?") {
                frames.push(LuaStackFrame {
                    source: source.to_string(),
                    line: None,
                    function: Some("?".to_string()),
                    raw: raw.to_string(),
                });
            }
            continue;
        };
        let function = suffix
            .strip_prefix(':')
            .map(str::trim)
            .and_then(|suffix| suffix.strip_prefix("in "))
            .map(str::to_string);
        frames.push(LuaStackFrame {
            source,
            line: Some(line_number),
            function,
            raw: raw.to_string(),
        });
    }
    LuaTraceback { message, frames }
}

/// Convert a Lua traceback for one generated Lua artifact to Rua locations.
///
/// `source_files` is indexed by `SourceRange::file`. For modules, select the
/// source map belonging to each generated chunk before calling this function;
/// a future project-level converter can dispatch frames across module maps.
pub fn convert_lua_traceback(
    traceback: &str,
    generated_source: &str,
    source_map: &[LuaSourceMapping],
    source_files: &[String],
) -> RuaTraceback {
    let parsed = parse_lua_traceback(traceback);
    RuaTraceback {
        message: parsed.message,
        frames: parsed
            .frames
            .into_iter()
            .map(|lua| convert_lua_frame(lua, generated_source, source_map, source_files))
            .collect(),
    }
}

/// Convert one parsed Lua frame through a generated source map.
pub fn convert_lua_frame(
    lua: LuaStackFrame,
    generated_source: &str,
    source_map: &[LuaSourceMapping],
    source_files: &[String],
) -> RuaStackFrame {
    let rua_range = lua.line.and_then(|line| {
        source_map
            .iter()
            .filter(|mapping| mapping_contains_line(generated_source, mapping, line))
            .min_by_key(|mapping| {
                (
                    mapping
                        .generated_end
                        .saturating_sub(mapping.generated_start),
                    mapping.generated_start,
                )
            })
            .map(|mapping| mapping.source)
    });
    let rua_file_id = rua_range.map(|range| range.file);
    let rua_file = rua_file_id.map(|file| {
        source_files
            .get(file as usize)
            .cloned()
            .unwrap_or_else(|| format!("<file {file}>"))
    });
    RuaStackFrame {
        lua,
        rua_file,
        rua_file_id,
        rua_range,
    }
}

fn mapping_contains_line(source: &str, mapping: &LuaSourceMapping, line: usize) -> bool {
    if mapping.generated_start >= mapping.generated_end || line == 0 {
        return false;
    }
    let start = line_at(source, mapping.generated_start);
    let end = line_at(source, mapping.generated_end.saturating_sub(1));
    start <= line && line <= end
}

fn line_at(source: &str, offset: usize) -> usize {
    let end = offset.min(source.len());
    1 + source.as_bytes()[..end]
        .iter()
        .filter(|byte| **byte == b'\n')
        .count()
}

/// Parse a location prefix while allowing colons in paths (for example
/// `C:\\work\\main.lua:12: in main chunk`). The returned suffix starts at the
/// colon following the line number.
fn parse_location(value: &str) -> Option<(String, usize, &str)> {
    let bytes = value.as_bytes();
    for colon in (0..bytes.len()).filter(|index| bytes[*index] == b':') {
        let digits_start = colon + 1;
        let mut digits_end = digits_start;
        while digits_end < bytes.len() && bytes[digits_end].is_ascii_digit() {
            digits_end += 1;
        }
        if digits_end == digits_start {
            continue;
        }
        if digits_end < bytes.len() && bytes[digits_end] != b':' {
            continue;
        }
        let line = value[digits_start..digits_end].parse().ok()?;
        let source = value[..colon].trim();
        if source.is_empty() {
            continue;
        }
        return Some((source.to_string(), line, &value[digits_end..]));
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mapping(start: usize, end: usize, line: usize, file: u32) -> LuaSourceMapping {
        LuaSourceMapping {
            generated_start: start,
            generated_end: end,
            source: SourceRange {
                start: 0,
                len: 4,
                line,
                file,
            },
        }
    }

    #[test]
    fn parses_error_location_and_stack_frames() {
        let traceback = "lua: main.lua:12: boom\nstack traceback:\n\tmain.lua:12: in local 'run'\n\t[C]: in ?\n";
        let parsed = parse_lua_traceback(traceback);
        assert_eq!(parsed.message, "boom");
        assert_eq!(parsed.frames.len(), 3);
        assert_eq!(parsed.frames[0].source, "main.lua");
        assert_eq!(parsed.frames[0].line, Some(12));
        assert_eq!(parsed.frames[1].function.as_deref(), Some("local 'run'"));
        assert_eq!(parsed.frames[2].line, None);
    }

    #[test]
    fn parses_windows_paths_without_treating_drive_as_line() {
        let parsed = parse_lua_traceback("C:\\work\\main.lua:7: boom\n");
        assert_eq!(parsed.frames[0].source, "C:\\work\\main.lua");
        assert_eq!(parsed.frames[0].line, Some(7));
    }

    #[test]
    fn keeps_colon_digits_in_error_message_out_of_location() {
        let parsed = parse_lua_traceback("lua: main.lua:7: status:42\n");
        assert_eq!(parsed.message, "status:42");
        assert_eq!(parsed.frames[0].source, "main.lua");
        assert_eq!(parsed.frames[0].line, Some(7));
    }

    #[test]
    fn converts_generated_line_to_rua_file_and_range() {
        let source = "-- header\nlocal a = 1\nlocal b = 2\n";
        let maps = [mapping(20, 31, 3, 1)];
        let files = vec!["main.rua".to_string(), "api.rua".to_string()];
        let converted = convert_lua_traceback(
            "lua: generated.lua:3: boom\nstack traceback:\n\tgenerated.lua:1: in main chunk\n",
            source,
            &maps,
            &files,
        );
        assert_eq!(converted.frames[0].rua_file.as_deref(), Some("api.rua"));
        assert_eq!(converted.frames[0].rua_file_id, Some(1));
        assert_eq!(converted.frames[0].rua_range.unwrap().line, 3);
        assert!(converted.frames[1].rua_range.is_none());
    }

    #[test]
    fn leaves_synthetic_and_c_frames_unmapped() {
        let converted = convert_lua_traceback(
            "lua: generated.lua:1: boom\nstack traceback:\n\t[C]: in ?\n",
            "-- generated\n",
            &[],
            &[],
        );
        assert!(
            converted
                .frames
                .iter()
                .all(|frame| frame.rua_range.is_none())
        );
    }
}
