//! Lua traceback parsing and generated-to-Rua stack conversion.
//!
//! Lua reports source locations as chunk paths plus 1-based line numbers. The
//! compiler source map uses generated byte offsets, so this module keeps the
//! conversion at the host boundary: parse the Lua text, resolve each generated
//! line through the source map, and preserve frames that belong to the runtime
//! or an unmapped generated region.

use crate::{codegen::LuaSourceMapping, token::SourceRange};

/// One frame parsed from Lua's human-readable traceback.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LuaStackFrame {
    /// Chunk path reported by Lua, for example `main.lua` or `[C]`.
    pub source: String,
    /// 1-based Lua line, when the frame has one.
    pub line: Option<usize>,
    /// Text following `in`, kept without guessing whether it is a local or
    /// global function.
    pub function: Option<String>,
    /// Original frame line, useful for diagnostics and unknown Lua formats.
    pub raw: String,
}

/// A parsed Lua traceback before source-map conversion.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LuaTraceback {
    /// The error message, without the leading `lua:` prefix.
    pub message: String,
    /// Frames in the order reported by Lua. The first frame is the error
    /// location when the first traceback line contains a source location.
    pub frames: Vec<LuaStackFrame>,
}

/// One converted Rua frame. Unmapped Lua/runtime frames remain visible with
/// `rua_range == None`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RuaStackFrame {
    pub lua: LuaStackFrame,
    /// Source file path resolved from the source-file registry, if available.
    pub rua_file: Option<String>,
    /// Stable compiler source file identity, if the frame maps to Rua code.
    pub rua_file_id: Option<u32>,
    /// Source range anchored by code generation, if the frame maps to Rua.
    pub rua_range: Option<SourceRange>,
}

/// A Lua traceback with each frame resolved through a generated source map.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RuaTraceback {
    pub message: String,
    pub frames: Vec<RuaStackFrame>,
}

/// Reusable generated-Lua-line to Rua-source index.
///
/// Build this once for a generated chunk and retain it at the host boundary.
/// Lookups are O(1) and allocate nothing, which makes this suitable for hot
/// paths such as source-aware logging and sampling profilers.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct LuaSourceMapIndex {
    by_line: Vec<Option<SourceRange>>,
}

impl LuaSourceMapIndex {
    pub fn new(generated_source: &str, source_map: &[LuaSourceMapping]) -> Self {
        if source_map.is_empty() {
            return Self::default();
        }

        let line_starts = generated_line_starts(generated_source);
        let mut candidates: Vec<Option<IndexedMapping>> = vec![None; line_starts.len()];
        for mapping in source_map {
            if mapping.generated_start >= mapping.generated_end {
                continue;
            }
            let start_line = generated_line_at(
                &line_starts,
                generated_source.len(),
                mapping.generated_start,
            );
            let end_line = generated_line_at(
                &line_starts,
                generated_source.len(),
                mapping.generated_end.saturating_sub(1),
            );
            let candidate = IndexedMapping {
                priority: (
                    mapping
                        .generated_end
                        .saturating_sub(mapping.generated_start),
                    mapping.generated_start,
                ),
                source: mapping.source,
            };
            for slot in &mut candidates[start_line - 1..end_line] {
                if slot.is_none_or(|current| candidate.priority < current.priority) {
                    *slot = Some(candidate);
                }
            }
        }

        Self {
            by_line: candidates
                .into_iter()
                .map(|candidate| candidate.map(|candidate| candidate.source))
                .collect(),
        }
    }

    /// Resolve a 1-based generated Lua line to its original Rua range.
    pub fn map_line(&self, line: usize) -> Option<SourceRange> {
        self.by_line.get(line.checked_sub(1)?)?.as_ref().copied()
    }
}

#[derive(Clone, Copy)]
struct IndexedMapping {
    priority: (usize, usize),
    source: SourceRange,
}

/// Parse Lua's default traceback format.
///
/// This accepts both the initial error location (`lua: file.lua:12: message`)
/// and stack frames (`file.lua:12: in function 'name'`). Unknown lines are
/// ignored except for `[C]: in ?`-style frames, which are retained as unmapped
/// frames.
pub fn parse_lua_traceback(traceback: &str) -> LuaTraceback {
    let mut lines = traceback.lines();
    let first = lines.next().unwrap_or_default().trim();
    let message_line = first.strip_prefix("lua:").unwrap_or(first).trim();
    let (message, error_frame) = if let Some((source, line, suffix)) = parse_location(message_line)
    {
        (
            suffix
                .strip_prefix(':')
                .map(str::trim)
                .unwrap_or_default()
                .to_string(),
            Some(LuaStackFrame {
                source,
                line: Some(line),
                function: None,
                raw: first.to_string(),
            }),
        )
    } else {
        (message_line.to_string(), None)
    };

    let mut frames = Vec::new();
    if let Some(frame) = error_frame {
        frames.push(frame);
    }
    for line in lines {
        let raw = line.trim();
        if raw.is_empty() || raw == "stack traceback:" {
            continue;
        }
        let Some((source, line_number, suffix)) = parse_location(raw) else {
            if let Some(source) = raw.strip_suffix(": in ?") {
                frames.push(LuaStackFrame {
                    source: source.to_string(),
                    line: None,
                    function: Some("?".to_string()),
                    raw: raw.to_string(),
                });
            }
            continue;
        };
        let function = suffix
            .strip_prefix(':')
            .map(str::trim)
            .and_then(|suffix| suffix.strip_prefix("in "))
            .map(str::to_string);
        frames.push(LuaStackFrame {
            source,
            line: Some(line_number),
            function,
            raw: raw.to_string(),
        });
    }
    LuaTraceback { message, frames }
}

/// Convert a Lua traceback for one generated Lua artifact to Rua locations.
///
/// `source_files` is indexed by `SourceRange::file`. For modules, select the
/// source map belonging to each generated chunk before calling this function;
/// a future project-level converter can dispatch frames across module maps.
pub fn convert_lua_traceback(
    traceback: &str,
    generated_source: &str,
    source_map: &[LuaSourceMapping],
    source_files: &[String],
) -> RuaTraceback {
    let parsed = parse_lua_traceback(traceback);
    let source_index = LuaSourceMapIndex::new(generated_source, source_map);
    RuaTraceback {
        message: parsed.message,
        frames: parsed
            .frames
            .into_iter()
            .map(|lua| convert_lua_frame_with_index(lua, &source_index, source_files))
            .collect(),
    }
}

/// Convert one parsed Lua frame through a generated source map.
///
/// This convenience function builds a temporary [`LuaSourceMapIndex`]. Hosts
/// that convert locations repeatedly should retain an index and call
/// [`convert_lua_frame_with_index`] or [`LuaSourceMapIndex::map_line`].
pub fn convert_lua_frame(
    lua: LuaStackFrame,
    generated_source: &str,
    source_map: &[LuaSourceMapping],
    source_files: &[String],
) -> RuaStackFrame {
    let source_index = LuaSourceMapIndex::new(generated_source, source_map);
    convert_lua_frame_with_index(lua, &source_index, source_files)
}

/// Convert one Lua frame with an index retained by the host.
pub fn convert_lua_frame_with_index(
    lua: LuaStackFrame,
    source_index: &LuaSourceMapIndex,
    source_files: &[String],
) -> RuaStackFrame {
    let rua_range = lua.line.and_then(|line| source_index.map_line(line));
    let rua_file_id = rua_range.map(|range| range.file);
    let rua_file = rua_file_id.map(|file| {
        source_files
            .get(file as usize)
            .cloned()
            .unwrap_or_else(|| format!("<file {file}>"))
    });
    RuaStackFrame {
        lua,
        rua_file,
        rua_file_id,
        rua_range,
    }
}

fn generated_line_starts(source: &str) -> Vec<usize> {
    let mut starts = Vec::with_capacity(source.bytes().filter(|byte| *byte == b'\n').count() + 1);
    starts.push(0);
    starts.extend(
        source
            .bytes()
            .enumerate()
            .filter_map(|(offset, byte)| (byte == b'\n').then_some(offset + 1)),
    );
    starts
}

fn generated_line_at(line_starts: &[usize], source_len: usize, offset: usize) -> usize {
    let offset = offset.min(source_len);
    line_starts.partition_point(|start| *start <= offset)
}

#[cfg(test)]
fn reference_mapping_for_line(
    source: &str,
    source_map: &[LuaSourceMapping],
    line: usize,
) -> Option<SourceRange> {
    source_map
        .iter()
        .filter(|mapping| reference_mapping_contains_line(source, mapping, line))
        .min_by_key(|mapping| {
            (
                mapping
                    .generated_end
                    .saturating_sub(mapping.generated_start),
                mapping.generated_start,
            )
        })
        .map(|mapping| mapping.source)
}

#[cfg(test)]
fn reference_mapping_contains_line(source: &str, mapping: &LuaSourceMapping, line: usize) -> bool {
    if mapping.generated_start >= mapping.generated_end || line == 0 {
        return false;
    }
    let start = reference_line_at(source, mapping.generated_start);
    let end = reference_line_at(source, mapping.generated_end.saturating_sub(1));
    start <= line && line <= end
}

#[cfg(test)]
fn reference_line_at(source: &str, offset: usize) -> usize {
    let end = offset.min(source.len());
    1 + source.as_bytes()[..end]
        .iter()
        .filter(|byte| **byte == b'\n')
        .count()
}

/// Parse a location prefix while allowing colons in paths (for example
/// `C:\\work\\main.lua:12: in main chunk`). The returned suffix starts at the
/// colon following the line number.
fn parse_location(value: &str) -> Option<(String, usize, &str)> {
    let bytes = value.as_bytes();
    for colon in (0..bytes.len()).filter(|index| bytes[*index] == b':') {
        let digits_start = colon + 1;
        let mut digits_end = digits_start;
        while digits_end < bytes.len() && bytes[digits_end].is_ascii_digit() {
            digits_end += 1;
        }
        if digits_end == digits_start {
            continue;
        }
        if digits_end < bytes.len() && bytes[digits_end] != b':' {
            continue;
        }
        let line = value[digits_start..digits_end].parse().ok()?;
        let source = value[..colon].trim();
        if source.is_empty() {
            continue;
        }
        return Some((source.to_string(), line, &value[digits_end..]));
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mapping(start: usize, end: usize, line: usize, file: u32) -> LuaSourceMapping {
        LuaSourceMapping {
            generated_start: start,
            generated_end: end,
            source: SourceRange {
                start: 0,
                len: 4,
                line,
                file,
            },
        }
    }

    #[test]
    fn parses_error_location_and_stack_frames() {
        let traceback = "lua: main.lua:12: boom\nstack traceback:\n\tmain.lua:12: in local 'run'\n\t[C]: in ?\n";
        let parsed = parse_lua_traceback(traceback);
        assert_eq!(parsed.message, "boom");
        assert_eq!(parsed.frames.len(), 3);
        assert_eq!(parsed.frames[0].source, "main.lua");
        assert_eq!(parsed.frames[0].line, Some(12));
        assert_eq!(parsed.frames[1].function.as_deref(), Some("local 'run'"));
        assert_eq!(parsed.frames[2].line, None);
    }

    #[test]
    fn parses_windows_paths_without_treating_drive_as_line() {
        let parsed = parse_lua_traceback("C:\\work\\main.lua:7: boom\n");
        assert_eq!(parsed.frames[0].source, "C:\\work\\main.lua");
        assert_eq!(parsed.frames[0].line, Some(7));
    }

    #[test]
    fn keeps_colon_digits_in_error_message_out_of_location() {
        let parsed = parse_lua_traceback("lua: main.lua:7: status:42\n");
        assert_eq!(parsed.message, "status:42");
        assert_eq!(parsed.frames[0].source, "main.lua");
        assert_eq!(parsed.frames[0].line, Some(7));
    }

    #[test]
    fn source_map_index_matches_reference_lookup_for_every_line() {
        let source = "alpha\nbeta\ngamma\ndelta\n";
        let beta = source.find("beta").unwrap();
        let gamma = source.find("gamma").unwrap();
        let maps = [
            mapping(0, source.len(), 10, 0),
            mapping(beta, source.len(), 20, 1),
            mapping(beta, gamma - 1, 30, 2),
            mapping(gamma, gamma, 40, 3),
        ];
        let index = LuaSourceMapIndex::new(source, &maps);

        for line in 0..=source.lines().count() + 2 {
            assert_eq!(
                index.map_line(line),
                reference_mapping_for_line(source, &maps, line),
                "generated line {line}",
            );
        }
    }

    #[test]
    fn empty_source_map_index_has_no_locations() {
        let index = LuaSourceMapIndex::new("line one\nline two\n", &[]);
        assert_eq!(index.map_line(0), None);
        assert_eq!(index.map_line(1), None);
        assert_eq!(index.map_line(usize::MAX), None);
    }

    #[test]
    fn converts_generated_line_to_rua_file_and_range() {
        let source = "-- header\nlocal a = 1\nlocal b = 2\n";
        let maps = [mapping(20, 31, 3, 1)];
        let files = vec!["main.rua".to_string(), "api.rua".to_string()];
        let converted = convert_lua_traceback(
            "lua: generated.lua:3: boom\nstack traceback:\n\tgenerated.lua:1: in main chunk\n",
            source,
            &maps,
            &files,
        );
        assert_eq!(converted.frames[0].rua_file.as_deref(), Some("api.rua"));
        assert_eq!(converted.frames[0].rua_file_id, Some(1));
        assert_eq!(converted.frames[0].rua_range.unwrap().line, 3);
        assert!(converted.frames[1].rua_range.is_none());
    }

    #[test]
    fn leaves_synthetic_and_c_frames_unmapped() {
        let converted = convert_lua_traceback(
            "lua: generated.lua:1: boom\nstack traceback:\n\t[C]: in ?\n",
            "-- generated\n",
            &[],
            &[],
        );
        assert!(
            converted
                .frames
                .iter()
                .all(|frame| frame.rua_range.is_none())
        );
    }
}
