[workspace]
resolver = "2"
members = [
    "crates/rua-common",
    "crates/rua-ide",
    "crates/ruac",
]

[workspace.dependencies]
rua-common = { path = "crates/rua-common" }
rua-ide = { path = "crates/rua-ide" }
ruac = { path = "crates/ruac" }
rowan = "0.15"
crossbeam-channel = "0.5"
url = "2"
ignore = "0.4"
include_dir = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
