-- Generated by ruac (Rua -> Lua 5.5). Do not edit by hand.
local rt = require("rua_rt")
local identity, label, first, demo_let, demo_control_flow, describe_color, classify_message, match_with_wildcard, demo_patterns, demo_closures, demo_expressions, demo_iterators, demo_extern, demo_literals, demo_comments, demo_self_receivers, greet_someone, demo_trait_object, main, math, utils
---@class Point
---@field x integer
---@field y integer
---@field label string
local Point = {}
Point.__index = Point
---@class Marker
local Marker = {}
Marker.__index = Marker
---@class Container
---@generic T
---@field value T
local Container = {}
Container.__index = Container
---@class Wrapper
---@generic T
---@field inner { ok: T }|{ err: string }|nil
local Wrapper = {}
Wrapper.__index = Wrapper
---@class Color
local Color = {}
Color.__index = Color
---@class Message
local Message = {}
Message.__index = Message
---@class Option
local Option = {}
Option.__index = Option
---@class Result
local Result = {}
Result.__index = Result
---@class Person
---@field name string
local Person = {}
Person.__index = Person
---@class Counter
---@field value integer
local Counter = {}
Counter.__index = Counter

---@generic T
---@param value T
---@return T
function identity(value)
    return value
end

---@generic T
---@param value T
---@return string
function label(value)
    return value:name()
end

---@generic T
---@param value T
---@return T
function first(value)
    return value
end

function demo_let()
    local simple = 42
    ---@type integer
    local typed = 100
    local mutable = 0
    mutable = (mutable + 1)
    local inferred_bool = true
    local inferred_float = 3.14159
    local text = "hello"
    local x = 1
    local x = (x + 1)
    local x = (x * 2)
end

---@param n integer
---@return integer
function demo_control_flow(n)
    local sign
    if (n > 0) then
        sign = "positive"
    else
        if (n < 0) then
            sign = "negative"
        else
            sign = "zero"
        end
    end
    local abs
    if (n >= 0) then
        abs = n
    else
        abs = -n
    end
    local count = 0
    while (count < 10) do
        count = (count + 1)
        ::continue::
    end
    local sum = 0
    for i = 0, (10) - 1 do
        sum = (sum + i)
        ::continue::
    end
    for j = 1, 5 do
        sum = (sum + j)
        ::continue::
    end
    local result = 0
    while (count < 100) do
        count = (count + 1)
        result = count
        ::continue::
    end
    if (n == 0) then
        do
            return 0
        end
    end
    local even_sum = 0
    for i = 0, (20) - 1 do
        if (rt.irem(i, 2) ~= 0) then
            goto continue
        end
        even_sum = (even_sum + i)
        ::continue::
    end
    return (((abs + sum) + result) + even_sum)
end

---@param c Color
---@return string
function describe_color(c)
    local __t1 = c
    local __t1_done = false
    if not __t1_done then
        if __t1.tag == "Red" then
            return "red"
        end
    end
    if not __t1_done then
        if __t1.tag == "Green" then
            return "green"
        end
    end
    if not __t1_done then
        if __t1.tag == "Blue" then
            return "blue"
        end
    end
    if not __t1_done then
        if __t1.tag == "Rgb" then
            local r = __t1[1]
            local g = __t1[2]
            local b = __t1[3]
            return "custom"
        end
    end
    if not __t1_done then
        error("non-exhaustive match")
    end
end

---@param msg Message
---@return integer
function classify_message(msg)
    local __t2 = msg
    local __t2_done = false
    if not __t2_done then
        if __t2.tag == "Quit" then
            return 0
        end
    end
    if not __t2_done then
        if __t2.tag == "Move" then
            local x = __t2.x
            local y = __t2.y
            return (x + y)
        end
    end
    if not __t2_done then
        if __t2.tag == "Write" then
            local text = __t2[1]
            return rt.str["len"](text)
        end
    end
    if not __t2_done then
        if __t2.tag == "ChangeColor" then
            local r = __t2[1]
            local g = __t2[2]
            local b = __t2[3]
            return ((r + g) + b)
        end
    end
    if not __t2_done then
        error("non-exhaustive match")
    end
end

---@param x integer|nil
---@return integer
function match_with_wildcard(x)
    local __t3 = x
    local __t3_done = false
    if not __t3_done then
        if __t3 ~= nil then
            local v = __t3
            return v
        end
    end
    if not __t3_done then
        if __t3.tag == "None" then
            return 0
        end
    end
    if not __t3_done then
        error("non-exhaustive match")
    end
end

---@param maybe Point|nil
---@return integer
function demo_patterns(maybe)
    local __t4 = maybe
    if __t4 ~= nil then
        local p = __t4
        do
            return (p.x + p.y)
        end
    end
    local opt = 1
    while true do
        local __t5 = opt
        if __t5 ~= nil then
            local v = __t5
            if (v > 10) then
                opt = nil
            else
                opt = (v + 1)
            end
        else
            break
        end
        ::continue::
    end
    local num = 42
    local flag = true
    local _unused = 99
    return num
end

---@return integer
function demo_closures()
    local function increment(value)
        return (value + 1)
    end
    local function forty_two()
        return 42
    end
    local function add(a, b)
        return (a + b)
    end
    local base = 10
    local function offset(x)
        return (x + base)
    end
    return ((increment(forty_two()) + add(1, 2)) + offset(5))
end

---@return integer
function demo_expressions()
    local arithmetic = ((1 + (2 * 3)) - rt.idiv(4, 2))
    local comparison = ((5 > 3) and (4 < 10))
    local logical = (not false or true)
    local p = Point.new(3, 4, "demo")
    local px = p.x
    local py = p.y
    local c = setmetatable({ value = rt.vec({ [0] = 1, [1] = 2, [2] = 3, n = 3 }) }, Container)
    local origin = setmetatable({ x = 0, y = 0, label = "origin" }, Point)
    for _ = 0, (5) - 1 do
        ::continue::
    end
    local block_value
    local a = 10
    local b = 20
    block_value = (a + b)
    local conditional
    if (px > 0) then
        conditional = px
    else
        conditional = 0
    end
    return ((((arithmetic + px) + py) + block_value) + conditional)
end

---@return integer
function demo_iterators()
    local values = rt.vec({ [0] = 1, [1] = 2, [2] = 3, [3] = 4, [4] = 5, n = 5 })
    ---@type integer[]
    local doubled
    local __t6 = values
    local __t7 = rt.vec({ n = 0 })
    for __t9 = 0, __t6.n - 1 do
        local __t8 = __t6[__t9]
        local __t10 = true
        if __t10 then
            local __t11
            do
                local x = __t8
                __t11 = (x * 2)
            end
            __t8 = __t11
        end
        if __t10 then
            local __t12
            do
                local x = __t8
                __t12 = (x > 5)
            end
            if not __t12 then __t10 = false end
        end
        if __t10 then
            __t7[__t7.n] = __t8
            __t7.n = __t7.n + 1
        end
    end
    doubled = __t7
    local total
    local __t13 = values
    local __t14 = 0
    for __t16 = 0, __t13.n - 1 do
        local __t15 = __t13[__t16]
        local __t17 = true
        if __t17 then
            local __t18
            do
                local acc = __t14
                local x = __t15
                __t18 = (acc + x)
            end
            __t14 = __t18
        end
    end
    total = __t14
    ---@type integer|nil
    local __t19
    local __t20 = values
    local __t21 = nil
    for __t23 = 0, __t20.n - 1 do
        local __t22 = __t20[__t23]
        local __t24 = true
        if __t24 then
            local __t25
            do
                local x = __t22
                __t25 = (x > 3)
            end
            if __t25 then __t21 = __t22; break end
        end
    end
    __t19 = __t21
    local function __t26(v)
        return v
    end
    local found = __t19:map(__t26)
    local has_big
    local __t27 = values
    local __t28 = false
    for __t30 = 0, __t27.n - 1 do
        local __t29 = __t27[__t30]
        local __t31 = true
        if __t31 then
            local __t32
            do
                local x = __t29
                __t32 = (x > 10)
            end
            if __t32 then __t28 = true; break end
        end
    end
    has_big = __t28
    local all_small
    local __t33 = values
    local __t34 = true
    for __t36 = 0, __t33.n - 1 do
        local __t35 = __t33[__t36]
        local __t37 = true
        if __t37 then
            local __t38
            do
                local x = __t35
                __t38 = (x < 100)
            end
            if not __t38 then __t34 = false; break end
        end
    end
    all_small = __t34
    local count
    local __t39 = values
    local __t40 = 0
    for __t42 = 0, __t39.n - 1 do
        local __t41 = __t39[__t42]
        local __t43 = true
        if __t43 then
            local __t44
            do
                local x = __t41
                __t44 = (rt.irem(x, 2) == 0)
            end
            if not __t44 then __t43 = false end
        end
        if __t43 then
            __t40 = __t40 + 1
        end
    end
    count = __t40
    return total
end

function demo_extern()
    log(rt.str["to_string"]("LSP demo is running!"))
    local msg = format("hello {}", rt.str["to_string"]("world"))
end

function demo_literals()
    local zero = 0
    local integer = 12345
    local negative = -42
    local fraction = 3.14159
    local t = true
    local f = false
    local plain = "hello world"
    local quote = "say \"hello\""
    local newline = "first\nsecond"
    local path = "c:\\tmp\\rua"
    local unicode = "你好世界"
end

---@return integer
function demo_comments()
    local x = 1
    return x
end

---@return integer
function demo_self_receivers()
    local c = setmetatable({ value = 10 }, Counter)
    local val = c:read()
    return val
end

---@param g Greet
---@return string
function greet_someone(g)
    return g:hello()
end

---@param person Person
---@return string
function demo_trait_object(person)
    return greet_someone(person)
end

function main()
    local origin = Point.new(0, 0, "origin")
    local dist = origin:distance_sq()
    local p = Point.new(3, 4, "moving")
    p:translate(1, 2)
    local red = setmetatable({ tag = "Red" }, Color)
    describe_color(red)
    local rgb = setmetatable({ tag = "Rgb", 255, 128, 0 }, Color)
    describe_color(rgb)
    local msg = setmetatable({ tag = "Move", x = 10, y = 20 }, Message)
    classify_message(msg)
    local alice = setmetatable({ name = "Alice" }, Person)
    alice:hello()
    greet_someone(alice)
    local sum = math.add(3, 4)
    local product = math.multiply(5, 6)
    utils.greet("Bob")
    demo_control_flow(42)
    demo_iterators()
    demo_closures()
    demo_patterns(nil)
    demo_expressions()
    demo_trait_object(alice)
    demo_self_receivers()
    demo_extern()
    demo_literals()
    demo_comments()
end

math = {}
do
    local add, multiply, trig

---@param a integer
---@param b integer
---@return integer
    function add(a, b)
        return (a + b)
    end

---@param a integer
---@param b integer
---@return integer
    function multiply(a, b)
        return (a * b)
    end

    trig = {}
    do
        local sin

---@param _x number
---@return number
        function sin(_x)
            return 0.0
        end
        trig.sin = sin
    end
    math.add = add
    math.multiply = multiply
    math.trig = trig
end

utils = {}
do
    local greet

---@param name string
---@return string
    function greet(name)
        return rt.format("Hi, {}!", name)
    end
    utils.greet = greet
end

---@param x integer
---@param y integer
---@param label string
---@return Point
function Point.new(x, y, label)
    return setmetatable({ x = x, y = y, label = label }, Point)
end

---@return integer
function Point:distance_sq()
    return ((self.x * self.x) + (self.y * self.y))
end

---@param dy integer
function Point:translate(dx, dy)
    self.x = (self.x + dx)
    self.y = (self.y + dy)
end

---@return string
function Person:name()
    return self.name
end

---@return string
function Person:hello()
    return rt.format("Hello, {}!", self.name)
end

---@return string
function Person:bye()
    return rt.str["to_string"]("bye")
end

---@return integer
function Counter:take()
    return self.value
end

---@return integer
function Counter:read()
    return self.value
end

function Counter:increment()
    self.value = (self.value + 1)
end

function Counter:reset()
    self.value = 0
end

main()
