-- Generated by ruac (Rua -> Lua 5.5). Do not edit by hand.
local rt = require("rua_rt")
---@class Point
---@field x integer
---@field y integer
---@field label string
local Point = {}
Point.__index = Point
---@class Marker
local Marker = {}
Marker.__index = Marker
---@class Container
---@generic T
---@field value T
local Container = {}
Container.__index = Container
---@class Wrapper
---@generic T
---@field inner T|nil, string|nil|nil
local Wrapper = {}
Wrapper.__index = Wrapper
---@class Color
local Color = {}
Color.__index = Color
---@class Message
local Message = {}
Message.__index = Message
---@class Person
---@field name string
local Person = {}
Person.__index = Person
---@class Counter
---@field value integer
local Counter = {}
Counter.__index = Counter
local log = log or function(...) end
local format = format or function(...) end

---@class math
local math = {}

---@return integer
function math.add(a, b)
    return a + b
end

---@return integer
function math.multiply(a, b)
    return a * b
end

---@class trig
local trig = {}

---@return number
function trig.sin(_x)
    return 0.0
end

---@class utils
local utils = {}

---@return string
function utils.greet(name)
    return rt.format("Hi, {}!", name)
end

---@generic T
---@return T
local function identity(value)
    return value
end

---@generic T
---@return string
local function label(value)
    return value:name()
end

---@generic T
---@return T
local function first(value)
    return value
end

local function demo_let()
    local simple = 42
    ---@type integer
    local typed = 100
    local mutable = 0
    mutable = mutable + 1
    local inferred_bool = true
    local inferred_float = 3.14159
    local text = "hello"
    local x = 1
    local x = x + 1
    local x = x * 2
end

---@return integer
local function demo_control_flow(n)
    local sign
    if n > 0 then
        sign = "positive"
    else
        if n < 0 then
            sign = "negative"
        else
            sign = "zero"
        end
    end
    local abs
    if n >= 0 then
        abs = n
    else
        abs = -n
    end
    local count = 0
    while count < 10 do
        count = count + 1
    end
    local sum = 0
    for i = 0, 9 do
        sum = sum + i
    end
    for j = 1, 5 do
        sum = sum + j
    end
    local result = 0
    while count < 100 do
        count = count + 1
        result = count
    end
    if n == 0 then
        do
            return 0
        end
    end
    local even_sum = 0
    for i = 0, 19 do
        if rt.irem(i, 2) ~= 0 then
            goto continue
        end
        even_sum = even_sum + i
        ::continue::
    end
    return abs + sum + result + even_sum
end

---@return string
local function describe_color(c)
    local __t1 = c
    if __t1.tag == "Red" then
        return "red"
    elseif __t1.tag == "Green" then
        return "green"
    elseif __t1.tag == "Blue" then
        return "blue"
    elseif __t1.tag == "Rgb" then
        local r = __t1[1]
        local g = __t1[2]
        local b = __t1[3]
        return "custom"
    else
        error("non-exhaustive match")
    end
end

---@return integer
local function classify_message(msg)
    local __t2 = msg
    if __t2.tag == "Quit" then
        return 0
    elseif __t2.tag == "Move" then
        local x = __t2.x
        local y = __t2.y
        return x + y
    elseif __t2.tag == "Write" then
        local text = __t2[1]
        return rt.str["len"](text)
    elseif __t2.tag == "ChangeColor" then
        local r = __t2[1]
        local g = __t2[2]
        local b = __t2[3]
        return r + g + b
    else
        error("non-exhaustive match")
    end
end

---@return integer
local function match_with_wildcard(x)
    local __t3 = x
    if __t3 ~= nil then
        local v = __t3
        return v
    elseif __t3.tag == "None" then
        return 0
    else
        error("non-exhaustive match")
    end
end

---@return integer
local function demo_patterns(maybe)
    local __t4 = maybe
    if __t4 ~= nil then
        local p = __t4
        do
            return p.x + p.y
        end
    end
    local opt = 1
    while true do
        local __t5 = opt
        if __t5 ~= nil then
            local v = __t5
            if v > 10 then
                opt = nil
            else
                opt = v + 1
            end
        else
            break
        end
    end
    local num = 42
    local flag = true
    local _unused = 99
    return num
end

---@return integer
local function demo_closures()
    local function increment(value)
        return value + 1
    end
    local function forty_two()
        return 42
    end
    local function add(a, b)
        return a + b
    end
    local base = 10
    local function offset(x)
        return x + base
    end
    return increment(forty_two()) + add(1, 2) + offset(5)
end

---@return integer
local function demo_expressions()
    local arithmetic = 1 + 2 * 3 - rt.idiv(4, 2)
    local comparison = 5 > 3 and 4 < 10
    local logical = not false or true
    local p = Point.new(3, 4, "demo")
    local px = p.x
    local py = p.y
    local c = setmetatable({ value = rt.vec({ [0] = 1, [1] = 2, [2] = 3, n = 3 }) }, Container)
    local origin = setmetatable({ x = 0, y = 0, label = "origin" }, Point)
    for _ = 0, 4 do
    end
    local block_value
    local a = 10
    local b = 20
    block_value = a + b
    local conditional
    if px > 0 then
        conditional = px
    else
        conditional = 0
    end
    return arithmetic + px + py + block_value + conditional
end

---@return integer
local function demo_iterators()
    local values = rt.vec({ [0] = 1, [1] = 2, [2] = 3, [3] = 4, [4] = 5, n = 5 })
    ---@type integer[]
    local doubled
    local __t6 = values
    local __t7 = rt.vec({ n = 0 })
    for __t9 = 0, __t6.n - 1 do
        local __t8 = __t6[__t9]
        local __t10 = true
        if __t10 then
            local __t11
            do
                local x = __t8
                __t11 = x * 2
            end
            __t8 = __t11
        end
        if __t10 then
            local __t12
            do
                local x = __t8
                __t12 = x > 5
            end
            if not __t12 then __t10 = false end
        end
        if __t10 then
            __t7[__t7.n] = __t8
            __t7.n = __t7.n + 1
        end
    end
    doubled = __t7
    local total
    local __t13 = values
    local __t14 = 0
    for __t16 = 0, __t13.n - 1 do
        local __t15 = __t13[__t16]
        local __t17 = true
        if __t17 then
            local __t18
            do
                local acc = __t14
                local x = __t15
                __t18 = acc + x
            end
            __t14 = __t18
        end
    end
    total = __t14
    ---@type integer|nil
    local __t19
    local __t20 = values
    local __t21 = nil
    for __t23 = 0, __t20.n - 1 do
        local __t22 = __t20[__t23]
        local __t24 = true
        if __t24 then
            local __t25
            do
                local x = __t22
                __t25 = x > 3
            end
            if __t25 then __t21 = __t22; break end
        end
    end
    __t19 = __t21
    local function __t26(v)
        return v
    end
    local __t27 = __t19
    if __t27 ~= nil then
    end
    local found = __t27
    local has_big
    local __t28 = values
    local __t29 = false
    for __t31 = 0, __t28.n - 1 do
        local __t30 = __t28[__t31]
        local __t32 = true
        if __t32 then
            local __t33
            do
                local x = __t30
                __t33 = x > 10
            end
            if __t33 then __t29 = true; break end
        end
    end
    has_big = __t29
    local all_small
    local __t34 = values
    local __t35 = true
    for __t37 = 0, __t34.n - 1 do
        local __t36 = __t34[__t37]
        local __t38 = true
        if __t38 then
            local __t39
            do
                local x = __t36
                __t39 = x < 100
            end
            if not __t39 then __t35 = false; break end
        end
    end
    all_small = __t35
    local count
    local __t40 = values
    local __t41 = 0
    for __t43 = 0, __t40.n - 1 do
        local __t42 = __t40[__t43]
        local __t44 = true
        if __t44 then
            local __t45
            do
                local x = __t42
                __t45 = rt.irem(x, 2) == 0
            end
            if not __t45 then __t44 = false end
        end
        if __t44 then
            __t41 = __t41 + 1
        end
    end
    count = __t41
    return total
end

local function demo_extern()
    log("LSP demo is running!")
    local msg = format("hello {}", "world")
end

local function demo_literals()
    local zero = 0
    local integer = 12345
    local negative = -42
    local fraction = 3.14159
    local t = true
    local f = false
    local plain = "hello world"
    local quote = "say \"hello\""
    local newline = "first\nsecond"
    local path = "c:\\tmp\\rua"
    local unicode = "你好世界"
end

---@return integer
local function demo_comments()
    local x = 1
    return x
end

---@return integer
local function demo_self_receivers()
    local c = setmetatable({ value = 10 }, Counter)
    local val = c:read()
    return val
end

---@return string
local function greet_someone(g)
    return g:hello()
end

---@return string
local function demo_trait_object(person)
    return greet_someone(person)
end

---@return string|nil, string|nil
local function load_config(path)
    if path == "" then
        return nil, "empty path"
    else
        return rt.format("config from {}", path)
    end
end

---@return integer|nil, string|nil
local function parse_int(raw)
    return 42
end

---@return integer|nil, string|nil
local function load_and_parse(path)
    local config, __t46 = load_config(path)
    if __t46 ~= nil then return nil, __t46 end
    if config == nil then return nil end
    local value, __t47 = parse_int(config)
    if __t47 ~= nil then return nil, __t47 end
    if value == nil then return nil end
    return value + 1
end

---@return integer|nil
local function maybe_double(x)
    local v = x
    if v == nil then return nil end
    return v * 2
end

---@return integer|nil
local function chain_option(a, b)
    local va = a
    if va == nil then return nil end
    local vb = b
    if vb == nil then return nil end
    return va + vb
end

---@return integer
local function demo_arithmetic()
    local int_sum = 1 + 2 + 3
    local float_sum = 1.5 + 2.5
    local mixed = 1 + 2.5
    local greeting = (("hello" .. " ") .. "world")
    return int_sum
end

local function main()
    local origin = Point.new(0, 0, "origin")
    local dist = origin:distance_sq()
    local p = Point.new(3, 4, "moving")
    p:translate(1, 2)
    local red = setmetatable({ tag = "Red" }, Color)
    describe_color(red)
    local rgb = setmetatable({ tag = "Rgb", 255, 128, 0 }, Color)
    describe_color(rgb)
    local msg = setmetatable({ tag = "Move", x = 10, y = 20 }, Message)
    classify_message(msg)
    local alice = setmetatable({ name = "Alice" }, Person)
    alice:hello()
    greet_someone(alice)
    local sum = math.add(3, 4)
    local product = math.multiply(5, 6)
    utils.greet("Bob")
    demo_control_flow(42)
    demo_iterators()
    demo_closures()
    demo_patterns(nil)
    demo_expressions()
    demo_trait_object(alice)
    demo_self_receivers()
    demo_extern()
    demo_literals()
    local config_result = load_and_parse("app.rua")
    local doubled = maybe_double(21)
    local chained = chain_option(1, 2)
    local none_propagate = chain_option(nil, 5)
    demo_arithmetic()
    demo_comments()
end

---@return Point
function Point.new(x, y, label)
    return setmetatable({ x = x, y = y, label = label }, Point)
end

---@return integer
function Point:distance_sq()
    return self.x * self.x + self.y * self.y
end

function Point:translate(dx, dy)
    self.x = self.x + dx
    self.y = self.y + dy
end

---@return string
function Person:name()
    return self.name
end

---@return string
function Person:hello()
    return rt.format("Hello, {}!", self.name)
end

---@return string
function Person:bye()
    return "bye"
end

---@return integer
function Counter:take()
    return self.value
end

---@return integer
function Counter:read()
    return self.value
end

function Counter:increment()
    self.value = self.value + 1
end

function Counter:reset()
    self.value = 0
end

main()
