-- Generated by ruac (Rua -> Lua 5.5). Do not edit by hand.
local rt = require("rua_rt")
local identity, label, first, demo_let, demo_control_flow, describe_color, classify_message, match_with_wildcard, demo_patterns, demo_closures, demo_expressions, demo_iterators, demo_extern, demo_literals, demo_comments, demo_self_receivers, greet_someone, demo_trait_object, load_config, parse_int, load_and_parse, maybe_double, chain_option, demo_arithmetic, main, math, utils
---@class Point
---@field x integer
---@field y integer
---@field label string
local Point = {}
Point.__index = Point
---@class Marker
local Marker = {}
Marker.__index = Marker
---@class Container
---@generic T
---@field value T
local Container = {}
Container.__index = Container
---@class Wrapper
---@generic T
---@field inner { ok: T }|{ err: string }|nil
local Wrapper = {}
Wrapper.__index = Wrapper
---@class Color
local Color = {}
Color.__index = Color
---@class Message
local Message = {}
Message.__index = Message
---@class Option
local Option = {}
Option.__index = Option
---@class Result
local Result = {}
Result.__index = Result
---@class Person
---@field name string
local Person = {}
Person.__index = Person
---@class Counter
---@field value integer
local Counter = {}
Counter.__index = Counter
local log = log or function(...) end
local format = format or function(...) end

---@generic T
---@param value T
---@return T
function identity(value)
    return value
end

---@generic T
---@param value T
---@return string
function label(value)
    return value:name()
end

---@generic T
---@param value T
---@return T
function first(value)
    return value
end

function demo_let()
    local simple = 42
    ---@type integer
    local typed = 100
    local mutable = 0
    mutable = mutable + 1
    local inferred_bool = true
    local inferred_float = 3.14159
    local text = "hello"
    local x = 1
    local x = x + 1
    local x = x * 2
end

---@param n integer
---@return integer
function demo_control_flow(n)
    local sign
    if n > 0 then
        sign = "positive"
    else
        if n < 0 then
            sign = "negative"
        else
            sign = "zero"
        end
    end
    local abs
    if n >= 0 then
        abs = n
    else
        abs = -n
    end
    local count = 0
    while count < 10 do
        count = count + 1
    end
    local sum = 0
    for i = 0, 9 do
        sum = sum + i
    end
    for j = 1, 5 do
        sum = sum + j
    end
    local result = 0
    while count < 100 do
        count = count + 1
        result = count
    end
    if n == 0 then
        do
            return 0
        end
    end
    local even_sum = 0
    for i = 0, 19 do
        if rt.irem(i, 2) ~= 0 then
            goto continue
        end
        even_sum = even_sum + i
        ::continue::
    end
    return abs + sum + result + even_sum
end

---@param c Color
---@return string
function describe_color(c)
    local __t1, __t2 = c
    if __t1.tag == "Red" then
        return "red"
    elseif __t1.tag == "Green" then
        return "green"
    elseif __t1.tag == "Blue" then
        return "blue"
    elseif __t1.tag == "Rgb" then
        local r = __t1[1]
        local g = __t1[2]
        local b = __t1[3]
        return "custom"
    else
        error("non-exhaustive match")
    end
end

---@param msg Message
---@return integer
function classify_message(msg)
    local __t3, __t4 = msg
    if __t3.tag == "Quit" then
        return 0
    elseif __t3.tag == "Move" then
        local x = __t3.x
        local y = __t3.y
        return x + y
    elseif __t3.tag == "Write" then
        local text = __t3[1]
        return rt.str["len"](text)
    elseif __t3.tag == "ChangeColor" then
        local r = __t3[1]
        local g = __t3[2]
        local b = __t3[3]
        return r + g + b
    else
        error("non-exhaustive match")
    end
end

---@param x integer|nil
---@return integer
function match_with_wildcard(x)
    local __t5, __t6 = x
    if __t5 ~= nil then
        local v = __t5
        return v
    elseif __t5.tag == "None" then
        return 0
    else
        error("non-exhaustive match")
    end
end

---@param maybe Point|nil
---@return integer
function demo_patterns(maybe)
    local __t7 = maybe
    if __t7 ~= nil then
        local p = __t7
        do
            return p.x + p.y
        end
    end
    local opt = 1
    while true do
        local __t8 = opt
        if __t8 ~= nil then
            local v = __t8
            if v > 10 then
                opt = nil
            else
                opt = v + 1
            end
        else
            break
        end
    end
    local num = 42
    local flag = true
    local _unused = 99
    return num
end

---@return integer
function demo_closures()
    local function increment(value)
        return value + 1
    end
    local function forty_two()
        return 42
    end
    local function add(a, b)
        return a + b
    end
    local base = 10
    local function offset(x)
        return x + base
    end
    return increment(forty_two()) + add(1, 2) + offset(5)
end

---@return integer
function demo_expressions()
    local arithmetic = 1 + 2 * 3 - rt.idiv(4, 2)
    local comparison = 5 > 3 and 4 < 10
    local logical = not false or true
    local p = Point.new(3, 4, "demo")
    local px = p.x
    local py = p.y
    local c = setmetatable({ value = rt.vec({ [0] = 1, [1] = 2, [2] = 3, n = 3 }) }, Container)
    local origin = setmetatable({ x = 0, y = 0, label = "origin" }, Point)
    for _ = 0, 4 do
    end
    local block_value
    local a = 10
    local b = 20
    block_value = a + b
    local conditional
    if px > 0 then
        conditional = px
    else
        conditional = 0
    end
    return arithmetic + px + py + block_value + conditional
end

---@return integer
function demo_iterators()
    local values = rt.vec({ [0] = 1, [1] = 2, [2] = 3, [3] = 4, [4] = 5, n = 5 })
    ---@type integer[]
    local doubled
    local __t9 = values
    local __t10 = rt.vec({ n = 0 })
    for __t12 = 0, __t9.n - 1 do
        local __t11 = __t9[__t12]
        local __t13 = true
        if __t13 then
            local __t14
            do
                local x = __t11
                __t14 = x * 2
            end
            __t11 = __t14
        end
        if __t13 then
            local __t15
            do
                local x = __t11
                __t15 = x > 5
            end
            if not __t15 then __t13 = false end
        end
        if __t13 then
            __t10[__t10.n] = __t11
            __t10.n = __t10.n + 1
        end
    end
    doubled = __t10
    local total
    local __t16 = values
    local __t17 = 0
    for __t19 = 0, __t16.n - 1 do
        local __t18 = __t16[__t19]
        local __t20 = true
        if __t20 then
            local __t21
            do
                local acc = __t17
                local x = __t18
                __t21 = acc + x
            end
            __t17 = __t21
        end
    end
    total = __t17
    ---@type integer|nil
    local __t22
    local __t23 = values
    local __t24 = nil
    for __t26 = 0, __t23.n - 1 do
        local __t25 = __t23[__t26]
        local __t27 = true
        if __t27 then
            local __t28
            do
                local x = __t25
                __t28 = x > 3
            end
            if __t28 then __t24 = __t25; break end
        end
    end
    __t22 = __t24
    local function __t29(v)
        return v
    end
    local __t30 = __t22
    if __t30 ~= nil then
    end
    local found = __t30
    local has_big
    local __t31 = values
    local __t32 = false
    for __t34 = 0, __t31.n - 1 do
        local __t33 = __t31[__t34]
        local __t35 = true
        if __t35 then
            local __t36
            do
                local x = __t33
                __t36 = x > 10
            end
            if __t36 then __t32 = true; break end
        end
    end
    has_big = __t32
    local all_small
    local __t37 = values
    local __t38 = true
    for __t40 = 0, __t37.n - 1 do
        local __t39 = __t37[__t40]
        local __t41 = true
        if __t41 then
            local __t42
            do
                local x = __t39
                __t42 = x < 100
            end
            if not __t42 then __t38 = false; break end
        end
    end
    all_small = __t38
    local count
    local __t43 = values
    local __t44 = 0
    for __t46 = 0, __t43.n - 1 do
        local __t45 = __t43[__t46]
        local __t47 = true
        if __t47 then
            local __t48
            do
                local x = __t45
                __t48 = rt.irem(x, 2) == 0
            end
            if not __t48 then __t47 = false end
        end
        if __t47 then
            __t44 = __t44 + 1
        end
    end
    count = __t44
    return total
end

function demo_extern()
    log("LSP demo is running!")
    local msg = format("hello {}", "world")
end

function demo_literals()
    local zero = 0
    local integer = 12345
    local negative = -42
    local fraction = 3.14159
    local t = true
    local f = false
    local plain = "hello world"
    local quote = "say \"hello\""
    local newline = "first\nsecond"
    local path = "c:\\tmp\\rua"
    local unicode = "你好世界"
end

---@return integer
function demo_comments()
    local x = 1
    return x
end

---@return integer
function demo_self_receivers()
    local c = setmetatable({ value = 10 }, Counter)
    local val = c:read()
    return val
end

---@param g Greet
---@return string
function greet_someone(g)
    return g:hello()
end

---@param person Person
---@return string
function demo_trait_object(person)
    return greet_someone(person)
end

---@param path string
---@return { ok: string }|{ err: string }
function load_config(path)
    if path == "" then
        return nil, "empty path"
    else
        return rt.format("config from {}", path)
    end
end

---@param raw string
---@return { ok: integer }|{ err: string }
function parse_int(raw)
    return 42
end

---@param path string
---@return { ok: integer }|{ err: string }
function load_and_parse(path)
    local __t49, __t50 = load_config(path)
    if __t50 ~= nil then return nil, __t50 end
    if __t49 == nil then return nil end
    local config = __t49
    local __t51, __t52 = parse_int(config)
    if __t52 ~= nil then return nil, __t52 end
    if __t51 == nil then return nil end
    local value = __t51
    return value + 1
end

---@param x integer|nil
---@return integer|nil
function maybe_double(x)
    local __t53, __t54 = x
    if __t54 ~= nil then return nil, __t54 end
    if __t53 == nil then return nil end
    local v = __t53
    return v * 2
end

---@param a integer|nil
---@param b integer|nil
---@return integer|nil
function chain_option(a, b)
    local __t55, __t56 = a
    if __t56 ~= nil then return nil, __t56 end
    if __t55 == nil then return nil end
    local va = __t55
    local __t57, __t58 = b
    if __t58 ~= nil then return nil, __t58 end
    if __t57 == nil then return nil end
    local vb = __t57
    return va + vb
end

---@return integer
function demo_arithmetic()
    local int_sum = 1 + 2
    local float_sum = 1.5 + 2.5
    local mixed = 1 + 2.5
    local greeting = (("hello" .. " ") .. "world")
    return int_sum
end

function main()
    local origin = Point.new(0, 0, "origin")
    local dist = origin:distance_sq()
    local p = Point.new(3, 4, "moving")
    p:translate(1, 2)
    local red = setmetatable({ tag = "Red" }, Color)
    describe_color(red)
    local rgb = setmetatable({ tag = "Rgb", 255, 128, 0 }, Color)
    describe_color(rgb)
    local msg = setmetatable({ tag = "Move", x = 10, y = 20 }, Message)
    classify_message(msg)
    local alice = setmetatable({ name = "Alice" }, Person)
    alice:hello()
    greet_someone(alice)
    local sum = math.add(3, 4)
    local product = math.multiply(5, 6)
    utils.greet("Bob")
    demo_control_flow(42)
    demo_iterators()
    demo_closures()
    demo_patterns(nil)
    demo_expressions()
    demo_trait_object(alice)
    demo_self_receivers()
    demo_extern()
    demo_literals()
    local config_result = load_and_parse("app.rua")
    local doubled = maybe_double(21)
    local chained = chain_option(1, 2)
    local none_propagate = chain_option(nil, 5)
    demo_arithmetic()
    demo_comments()
end

math = {}
do
    local add, multiply, trig

---@param a integer
---@param b integer
---@return integer
    function add(a, b)
        return a + b
    end

---@param a integer
---@param b integer
---@return integer
    function multiply(a, b)
        return a * b
    end

    trig = {}
    do
        local sin

---@param _x number
---@return number
        function sin(_x)
            return 0.0
        end
        trig.sin = sin
    end
    math.add = add
    math.multiply = multiply
    math.trig = trig
end

utils = {}
do
    local greet

---@param name string
---@return string
    function greet(name)
        return rt.format("Hi, {}!", name)
    end
    utils.greet = greet
end

---@param x integer
---@param y integer
---@param label string
---@return Point
function Point.new(x, y, label)
    return setmetatable({ x = x, y = y, label = label }, Point)
end

---@return integer
function Point:distance_sq()
    return self.x * self.x + self.y * self.y
end

---@param dy integer
function Point:translate(dx, dy)
    self.x = self.x + dx
    self.y = self.y + dy
end

---@return string
function Person:name()
    return self.name
end

---@return string
function Person:hello()
    return rt.format("Hello, {}!", self.name)
end

---@return string
function Person:bye()
    return "bye"
end

---@return integer
function Counter:take()
    return self.value
end

---@return integer
function Counter:read()
    return self.value
end

function Counter:increment()
    self.value = self.value + 1
end

function Counter:reset()
    self.value = 0
end

main()
