-- rua_rt: minimal runtime shim for code generated by ruac (Rua -> Lua 5.5).
-- See docs/rua-design.md. Kept intentionally small and versioned because
-- generated artifacts treat these helpers as a runtime ABI.

local rt = {}

rt.ABI_VERSION = 1

local Result = {}
Result.__index = Result

function rt.result_ok(value)
    return setmetatable({ __rua_result = true, tag = "ok", value = value }, Result)
end

function rt.result_err(value)
    return setmetatable({ __rua_result = true, tag = "err", value = value }, Result)
end

function Result:is_ok()
    return self.tag == "ok"
end

function Result:is_err()
    return self.tag == "err"
end

function Result:unwrap()
    if self.tag == "err" then
        error(self.value, 2)
    end
    return self.value
end

function Result:unwrap_or(default)
    if self.tag == "ok" then
        return self.value
    end
    return default
end

-- Rust-ish `{}` / `{:?}` formatting. Very small: `{}` and `{:?}` both stringify
-- the next argument via tostring(); `{{`/`}}` are literal braces.
function rt.format(fmt, ...)
    local args = { ... }
    local n = 0
    local out = fmt:gsub("{{", "\0LB\0"):gsub("}}", "\0RB\0")
    out = out:gsub("{[:%w%.%?]*}", function()
        n = n + 1
        return tostring(args[n])
    end)
    out = out:gsub("\0LB\0", "{"):gsub("\0RB\0", "}")
    return out
end

function rt.print(fmt, ...)
    io.write(rt.format(fmt, ...))
end

function rt.println(fmt, ...)
    print(rt.format(fmt, ...))
end

-- Unrecoverable error (maps Rust `panic!`).
function rt.panic(msg)
    error(msg, 2)
end

-- Integer division truncating toward zero, matching Rust `i64 / i64` (Lua `//`
-- floors toward -inf, so they differ when exactly one operand is negative).
function rt.idiv(a, b)
    local q = a // b
    -- Correct the floored quotient up by one when it rounded the wrong way,
    -- i.e. when the operands have opposite signs and the division is inexact.
    if (a % b ~= 0) and ((a < 0) ~= (b < 0)) then
        q = q + 1
    end
    return q
end

-- Integer remainder matching Rust `i64 % i64` (result takes the sign of the
-- dividend), consistent with `rt.idiv`: a == rt.idiv(a,b) * b + rt.irem(a,b).
function rt.irem(a, b)
    local r = a % b
    -- Lua `%` takes the sign of the divisor; flip it back toward the dividend.
    if r ~= 0 and ((r < 0) ~= (a < 0)) then
        r = r - b
    end
    return r
end

-- Vec: 0-based storage (matching Rust indexing) with an `n` length field.
local Vec = {}
Vec.__index = Vec

function Vec:len()
    return self.n
end

function Vec:push(x)
    self[self.n] = x
    self.n = self.n + 1
end

function Vec:pop()
    if self.n == 0 then
        return nil
    end
    self.n = self.n - 1
    local x = self[self.n]
    self[self.n] = nil
    return x
end

function Vec:get(i)
    return self[i]
end

function Vec:set(i, x)
    self[i] = x
end

-- Wrap a `{ [0]=.., [1]=.., n=len }` table as a Vec (used by `vec![...]`).
function rt.vec(t)
    return setmetatable(t, Vec)
end

-- String: a small shim mapping Rust `String`/`str` methods to Lua. Generated
-- code calls `rt.str["method"](s, ...)`; the receiver is the first argument.
-- Lengths and indices are byte-based, matching Rust `&str`.
rt.str = {}

-- `to_string`/`to_owned`/`clone` on a `str`/`String` are identities in Lua
-- (strings are immutable values).
function rt.str.to_string(s)
    return s
end
rt.str.to_owned = rt.str.to_string
rt.str.clone = rt.str.to_string

function rt.str.len(s)
    return #s
end

function rt.str.is_empty(s)
    return #s == 0
end

function rt.str.to_uppercase(s)
    return (s:upper())
end

function rt.str.to_lowercase(s)
    return (s:lower())
end

function rt.str.trim(s)
    return (s:gsub("^%s*(.-)%s*$", "%1"))
end

function rt.str.trim_start(s)
    return (s:gsub("^%s*", ""))
end

function rt.str.trim_end(s)
    return (s:gsub("%s*$", ""))
end

function rt.str.contains(s, sub)
    return s:find(sub, 1, true) ~= nil
end

function rt.str.starts_with(s, p)
    return s:sub(1, #p) == p
end

function rt.str.ends_with(s, p)
    return p == "" or s:sub(-#p) == p
end

-- Literal (non-pattern) replace of every occurrence, matching Rust `.replace`.
function rt.str.replace(s, from, to)
    if from == "" then
        return s
    end
    local out, i = {}, 1
    local flen = #from
    while true do
        local a = s:find(from, i, true)
        if not a then
            out[#out + 1] = s:sub(i)
            break
        end
        out[#out + 1] = s:sub(i, a - 1)
        out[#out + 1] = to
        i = a + flen
    end
    return table.concat(out)
end

function rt.str.repeat_(s, n)
    if n <= 0 then
        return ""
    end
    return s:rep(n)
end
rt.str["repeat"] = rt.str.repeat_

-- `chars()` -> Vec of single-byte strings (0-based, like our Vec).
function rt.str.chars(s)
    local t = { n = #s }
    for i = 1, #s do
        t[i - 1] = s:sub(i, i)
    end
    return rt.vec(t)
end

-- `split(sep)` -> Vec of substrings (literal separator). Empty `sep` yields the
-- whole string as a single element.
function rt.str.split(s, sep)
    local t = { n = 0 }
    local function push(x)
        t[t.n] = x
        t.n = t.n + 1
    end
    if sep == "" then
        push(s)
        return rt.vec(t)
    end
    local i, slen = 1, #sep
    while true do
        local a = s:find(sep, i, true)
        if not a then
            push(s:sub(i))
            break
        end
        push(s:sub(i, a - 1))
        i = a + slen
    end
    return rt.vec(t)
end

-- HashMap: entries live in `d`, with `n` tracking the count. Method names are
-- kept out of the data table so keys can never collide with them.
local Map = {}
Map.__index = Map

function Map:insert(k, v)
    local old = self.d[k]
    if old == nil then
        self.n = self.n + 1
    end
    self.d[k] = v
    return old -- Rust returns the previous value as Option<V>
end

function Map:get(k)
    return self.d[k]
end

function Map:contains_key(k)
    return self.d[k] ~= nil
end

function Map:remove(k)
    local v = self.d[k]
    if v ~= nil then
        self.d[k] = nil
        self.n = self.n - 1
    end
    return v
end

function Map:len()
    return self.n
end

function rt.map()
    return setmetatable({ d = {}, n = 0 }, Map)
end

return rt
