import * as assert from "assert";
import * as fs from "fs";
import * as path from "path";
import * as vscode from "vscode";

interface ExtensionTestState {
  starts: number;
  stops: number;
  configurationNotifications: number;
  activeResources: number;
  command: string;
  args: string[];
  settings: {
    trace: string;
    workspaceSettings: Array<{
      projectIndex: number;
      workspaceFolder: string;
    }>;
  };
  workspaceFolders: string[];
}

async function state(): Promise<ExtensionTestState> {
  return vscode.commands.executeCommand<ExtensionTestState>("rua.__testState");
}

async function waitUntil(
  predicate: () => Promise<boolean>,
  message: string,
): Promise<void> {
  const deadline = Date.now() + 10_000;
  while (Date.now() < deadline) {
    if (await predicate()) {
      return;
    }
    await new Promise((resolve) => setTimeout(resolve, 50));
  }
  throw new Error(message);
}

export async function run(): Promise<void> {
  const extension = vscode.extensions.getExtension("BruceZeros.rua-lang");
  assert.ok(extension, "Rua extension is installed in the Extension Host");
  await extension.activate();

  const initial = await state();
  assert.strictEqual(initial.starts, 1);
  assert.strictEqual(initial.stops, 0);
  assert.strictEqual(initial.activeResources, 2);
  assert.strictEqual(initial.workspaceFolders.length, 2);
  assert.deepStrictEqual(initial.args, []);
  assert.ok(path.isAbsolute(initial.command));

  const firstFolder = vscode.workspace.workspaceFolders?.[0];
  const secondFolder = vscode.workspace.workspaceFolders?.[1];
  assert.ok(firstFolder);
  assert.ok(secondFolder);
  assert.strictEqual(
    initial.settings.workspaceSettings[0].projectIndex,
    0,
  );
  assert.strictEqual(
    initial.settings.workspaceSettings[0].workspaceFolder,
    firstFolder.uri.toString(),
  );
  assert.strictEqual(
    initial.settings.workspaceSettings[1].projectIndex,
    1,
  );
  assert.strictEqual(
    initial.settings.workspaceSettings[1].workspaceFolder,
    secondFolder.uri.toString(),
  );
  assert.strictEqual(initial.settings.trace, "off");

  const explorerMenu = extension.packageJSON.contributes.menus["explorer/context"];
  assert.ok(
    explorerMenu.some(
      (item: { command: string; when: string }) =>
        item.command === "rua.buildFile" && item.when === "resourceExtname == .rua",
    ),
    "Rua build command is available for .rua files in the Explorer context menu",
  );

  const requestsUri = vscode.Uri.joinPath(firstFolder.uri, "requests.rua");
  const requestsDocument = await vscode.workspace.openTextDocument(requestsUri);
  const associatedFunction = new vscode.Position(
    1,
    requestsDocument.lineAt(1).text.indexOf("new") + 1,
  );
  await waitUntil(async () => {
    const hovers = await vscode.commands.executeCommand<vscode.Hover[]>(
      "vscode.executeHoverProvider",
      requestsUri,
      associatedFunction,
    );
    return hovers.length > 0;
  }, "Rua hover provider did not resolve OrderRequest::new");
  const hovers = await vscode.commands.executeCommand<vscode.Hover[]>(
    "vscode.executeHoverProvider",
    requestsUri,
    associatedFunction,
  );
  assert.ok(
    hovers.some((hover) =>
      hover.contents.some((content) =>
        (typeof content === "string" ? content : content.value).includes(
          "fn new(",
        ),
      ),
    ),
    "associated-function hover contains its signature",
  );
  const definitions = await vscode.commands.executeCommand<
    Array<vscode.Location | vscode.LocationLink>
  >("vscode.executeDefinitionProvider", requestsUri, associatedFunction);
  assert.ok(definitions.length > 0, "associated function has a definition");
  const definitionUri =
    definitions[0] instanceof vscode.Location
      ? definitions[0].uri
      : definitions[0].targetUri;
  assert.strictEqual(
    fs.realpathSync.native(definitionUri.fsPath),
    fs.realpathSync.native(
      vscode.Uri.joinPath(firstFolder.uri, "domain", "order.rua").fsPath,
    ),
  );
  await vscode.commands.executeCommand("rua.openLocation", {
    uri: definitionUri.toString(),
    range: {
      start: { line: 3, character: 11 },
      end: { line: 3, character: 14 },
    },
  });
  const openedDefinition = vscode.window.activeTextEditor;
  assert.ok(openedDefinition, "type-definition command opens an editor");
  assert.strictEqual(
    fs.realpathSync.native(openedDefinition.document.uri.fsPath),
    fs.realpathSync.native(definitionUri.fsPath),
  );
  assert.strictEqual(requestsDocument.languageId, "rua");

  const source = vscode.Uri.joinPath(firstFolder.uri, "main.rua");
  const generated = vscode.Uri.joinPath(firstFolder.uri, "main.lua");
  assert.strictEqual(
    await vscode.commands.executeCommand<boolean>("rua.buildFile", source),
    true,
  );
  assert.ok(fs.existsSync(generated.fsPath), "Rua build command generated main.lua");
  assert.match(
    fs.readFileSync(generated.fsPath, "utf8"),
    /Generated by ruac/,
  );

  const config = vscode.workspace.getConfiguration("rua");
  await config.update(
    "trace.server",
    "messages",
    vscode.ConfigurationTarget.Workspace,
  );
  await waitUntil(
    async () => (await state()).configurationNotifications >= 1,
    "dynamic Rua configuration was not forwarded to the language server",
  );

  await vscode.commands.executeCommand("rua.restartServer");
  const restarted = await state();
  assert.strictEqual(restarted.starts, 2);
  assert.strictEqual(restarted.stops, 1);
  assert.strictEqual(restarted.activeResources, 2);
  assert.strictEqual(restarted.settings.trace, "messages");
  assert.strictEqual(restarted.workspaceFolders.length, 2);

  await vscode.commands.executeCommand("rua.__testDeactivate");
  const stopped = await state();
  assert.strictEqual(stopped.stops, 2);
  assert.strictEqual(stopped.activeResources, 0);
}
